#! /bin/bash

# 	0.1 Check for right usage & set up basic Script Variables
if [ "$#" != "4" ]; then

	echo -e ""
	echo -e "----------------------------------"
	echo -e " Open Foris SARKit - Remote Access Scripts, ${OSK_VERSION}"
	echo -e " Preparing K&C mosaics on a remote machine"
	echo -e " Developed by: Food and Agriculture Organization of the United Nations, Rome"
#	echo -e " Author: Andreas Vollrath"
	echo -e "----------------------------------"
	echo -e ""
	echo -e "----------------------------------"
	echo -e " Software dependencies:"
	echo -e "	- gdal-bin"
	echo -e "	- SAGA GIS"
	echo -e "----------------------------------"
	echo -e ""
	echo -e " syntax: osk_prepare_KC_mosaics <ISO3_country_code/area_of_interest> <year> <filtering> <texture>"
	echo -e ""
	echo -e " description of input parameters:"
	echo -e " output_folder		(output) pathname of the output folder"
 	echo -e " ISO3_country_code/area_of_interest	ISO3 country code or shapefile of your area of interest"
	echo -e " Year		Acquisition Year (2007,2008,2009 or 2010)"
	echo -e " filtering		Apply Multi-directional Lee Filter (Lee et al. 1998)"
	echo -e "			  Available choices:"
	echo -e "			  0: no filtering applied"
	echo -e "			  1: filter applied"
	echo -e " texture		Calculate Texture measures"
	echo -e "			  Available choices:"
	echo -e "			  0: no calculation applied"
	echo -e "			  1: texture measures will be applied"
	echo -e ""		
	echo -e ""

  	exit 1
else
	echo -e ""
	echo -e "----------------------------------"
	echo -e " Open Foris SAR Kit Remote, ${VERSION}"
	echo -e " Preparing K&C mosaics on a remote machine"
	echo -e " Developed by: Food and Agriculture Organization of the United Nations, Rome"
#	echo -e " Author: Andreas Vollrath"
	echo -e "----------------------------------"
	echo -e ""
	echo -e ""
fi

# start remote job
read -r -p "Type in the username of the remote machine: " USERNAME
read -r -p "Type in the (IP)-Address of the remote machine: " ADRESS
read -r -p "Type in the name of your Project (will be the folder in your remote home directory where the processed data will be stored): " PROJECT

#execute 
ssh -n -f ${USERNAME}@${ADRESS} "bash -c \"mkdir ~/${PROJECT}; nohup bash osk_prepare_KC_mosaic ~/${PROJECT}/ $1 $2 $3 $4 > log 2>&1 &\""
