#! /bin/bash

echo -e "*** Start remote Job ***"
echo -e "*** OpenSARKit, v.01  ***"
echo -e ""


# start remote job
read -r -p "Type in the username of the remote machine" USERNAME
read -r -p "Type in the (IP)-Address of the remote machine" ADRESS
read -r -p "Which country do you want to process? (english name)" COUNTRY

ssh -n -f ${USERNAME}@${ADRESS} "bash -c 'mkdir ~/${COUNTRY}; cd ~/${COUNTRY}; source ~/github/OpenSARKit_source.bash;nohup bash ~/github/OpenSARKit/bins/ASF/osk_path_ALOS_L1.5_preprocess_asf.sh . /data/home/Andreas.Vollrath/datasets/Uga/DEM/final_dem.tif > log 2>&1 &'"
