#! /bin/bash

# The MIT License (MIT)
# Copyright (c) 2016 Andreas Vollrath

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is furnished
# to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
# OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

#-------------------------------------------------------------------------------------------
# 	0.1 Check for right usage & set up basic Script Variables
if [ "$#" == "2" ]; then

	# source libs
	source ${OPENSARKIT}/lib/helpers_source

	echo -e "---------------------------------------------------------------------------"
	echo -e " Open SAR Toolkit, version ${OST_VERSION}"
	echo -e " Cancel an OST process"
	echo -e "---------------------------------------------------------------------------"

else

	echo -e "---------------------------------------------------------------------------"
	echo -e " Open SAR Toolkit, version ${OST_VERSION}"
	echo -e " Cancel an OST process"
	echo -e "---------------------------------------------------------------------------"

	echo -e ""
	echo -e " syntax: ost_cancel_proc <script name> <tmp folder> "
	echo -e ""
	echo -e " input parameters:"
	echo -e " script name			(input) OST processing command that should be killed"
	echo -e " tmp folder		(input) 	path to the temp folder"
	exit 1

fi

# get the PID

KILL=$(ps -ef | grep "$1" | grep -v grep | grep -v "ost_cancel_proc" | awk '{print $2}')
echo $KILL
# kill the process and its child processes
kill $(list_descendants $KILL | tr '\n' ' ') $KILL

# remove temp folder
rm -rf $2
echo "Process succesfully killed."
