#! /bin/bash


#-------------------------------------------------------------------------------------------	
# 	0.1 Check for right usage & set up basic Script Variables
if [ "$#" != "2" ]; then

	echo -e ""
	echo -e "----------------------------------"
	echo -e " OpenSARKit, v.01"
	echo -e " Preparing K&C mosaics"
	echo -e " Developed by: Food and Agriculture Organization of the United Nations, Rome"
#	echo -e " Author: Andreas Vollrath"
	echo -e "----------------------------------"
	echo -e ""
	echo -e " syntax: osk_download_SRTM <Area_of_Interest> <output_tif_file>" 
	echo -e ""
	echo -e " input parameters:"
	echo -e " Area_of_Interest	(input) Shapefile of your Area of interest (i.e. with ending .shp)"
	echo -e " output_tif_file		(output) final DEM file with tif ending (i.e. /path/DEM.tif)"
	echo -e ""
	echo -e "----------------------------------"
	echo -e " Software components:"
	echo -e "	- gdal-libraries"
	echo -e "	- ogr2ogr"
	echo -e "	- Spatialite/SQlite"
	echo -e "----------------------------------"
	echo -e ""
	exit 1
else
	echo -e ""
	echo -e "----------------------------------"
	echo -e " OpenSARKit, v.01"
	echo -e " Preparing K&C mosaics"
	echo -e " Developed by: Food and Agriculture Organization of the United Nations, Rome"
#	echo -e " Author: Andreas Vollrath"
	echo -e "----------------------------------"
	echo -e ""
	echo -e "----------------------------------"
	echo -e " Software components:"
	echo -e "	- gdal-libraries"
	echo -e "	- ogr2ogr"
	echo -e "	- Spatialite/SQlite"
	echo -e "----------------------------------"
	echo -e ""
	AOI=$1   
	PROC_DIR=`dirname $2`
	if [ -d ${PROC_DIR} ];then
		echo ""
	else
		mkdir -p ${PROC_DIR}
	fi


	TMP_DIR=${PROC_DIR}/TMP
	mkdir -p ${TMP_DIR}
	echo "Producing DEM in ${PROC_DIR}"
fi

# get layer name
LAYER=`ogrinfo ${AOI} | tail -1 | awk $'{print $2}'`

# create a vrt layer for consequent interect operation with ogr2ogr
echo "<OGRVRTDataSource>" > ${TMP_DIR}/intersect.vrt
echo "   <OGRVRTLayer name=\"${LAYER}\">" >> ${TMP_DIR}/intersect.vrt
echo "      <SrcDataSource>${AOI}</SrcDataSource>" >> ${TMP_DIR}/intersect.vrt
echo "   </OGRVRTLayer>" >> ${TMP_DIR}/intersect.vrt
echo "   <OGRVRTLayer name=\"srtm3_grid\">" >> ${TMP_DIR}/intersect.vrt
echo "      <SrcDataSource>${DB_GLOBAL}</SrcDataSource>" >> ${TMP_DIR}/intersect.vrt
echo "   </OGRVRTLayer>" >> ${TMP_DIR}/intersect.vrt
echo "</OGRVRTDataSource>" >> ${TMP_DIR}/intersect.vrt

# intersect with ogr2ogr
ogr2ogr -f "csv" ${TMP_DIR}/tiles.csv ${TMP_DIR}/intersect.vrt -dialect sqlite -sql "SELECT b.COL,b.ROW FROM ${LAYER} a, srtm3_grid b WHERE ST_Intersects(a.geometry, b.geometry)" 
# get tile list
cat ${TMP_DIR}/tiles.csv | tail -n +2 | tr ',' '\ ' > ${TMP_DIR}/srtm_list

while read LINE; do

	COL=`echo ${LINE} | awk $'{print $1}'`
	ROW=`echo ${LINE} | awk $'{print $2}'`


	if [ ${#ROW} == 1 ];then ROW=0$ROW;fi
	if [ ${#COL} == 1 ];then COL=0$COL;fi
	
	wget http://droppr.org/srtm/v4.1/6_5x5_TIFs/srtm_$COL"_"$ROW.zip
	unzip -o -q srtm_$COL"_"$ROW.zip -d ${TMP_DIR}/SRTM
	rm -f srtm_$COL"_"$ROW.zip

done < ${TMP_DIR}/srtm_list

# merge SRTM tiles
gdal_merge.py -o ${TMP_DIR}/tmp_dem.tif -n -32768 -a_nodata -32768 ${TMP_DIR}/SRTM/*.tif
# recalculate 0's to 1
gdal_calc.py -A ${TMP_DIR}/tmp_dem.tif --outfile=${TMP_DIR}/tmp_dem2.tif --calc="(A==0)*1 + (A!=0)*A " 
# change -32767 to 0's
gdal_calc.py -A ${TMP_DIR}/tmp_dem2.tif --outfile=${PROC_DIR}/DEM_SRTM3V4.1.tif --calc="(A==-32767)*0 + (A!=-32767)*A" --overwrite --NoDataValue=0

# remove Temporary Directoy
rm -rf ${TMP_DIR}

#---------------------------------
# To-dos 
#---------------------------------

# produce Gamma par file
# produce DORIS timing.dorisin
# maybe include SRTM1 via EarthExplorer
# maybe include ASTER DEM


