#!/bin/bash

TTY=`ps -ef | grep "/bin/bash /usr/local/bin/poft-sar-ALOS-KC-full" | grep -v "grep" | awk '{print $6}'`
echo $TTY
PROCESSES=`ps -ef | grep $TTY | awk '{print $2}' | tr '\n' ' '`
echo $PROCESSES
kill ${PROCESSES}