#! /bin/bash

# The MIT License (MIT)
# Copyright (c) 2016 Andreas Vollrath

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal 
# in the Software without restriction, including without limitation the rights 
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell 
# copies of the Software, and to permit persons to whom the Software is furnished
# to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE 
# OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# to dos
# secure download, assuring for connection time outs and see if md5sum test is feasible

# 	0.1 Check for right usage & set up basic Script Variables
if [ "$#" == "5" ];then

	echo -e ""
	echo -e "-------------------------------------------------------------"
	echo -e " Open Foris SARKit, version ${OSK_VERSION}"
	echo -e " This scripts download ALOS K&C mosaics based on the extent" 
	echo -e "  of a given a given shapefile or a country boundary"
	echo -e "------------------------------------------------------------"
	echo -e ""


	CRED_FILE=`readlink -f $5`
	# set up initial script variables
	mkdir -p $1
	OUT_DIR=`readlink -f $1` 

	ZIP_DIR=${OUT_DIR}/ZIP
	mkdir -p ${ZIP_DIR}
	YEAR=$3

	TMP_DIR=${OUT_DIR}/.TMP$3
	mkdir -p ${TMP_DIR}
	# source libs
	source ${OPENSARKIT}/lib/helpers_source

elif [ "$#" != "4" ]; then

	echo -e "-------------------------------------------------------------"
	echo -e " Open Foris SAR Toolkit, version ${OSK_VERSION}"
	echo -e " This script downloads and processes ALOS K&C mosaics based on the" 
	echo -e " extent of a given a given shapefile or a country boundary"
	echo -e "------------------------------------------------------------"
	echo -e ""
	echo -e "----------------------------------"
	echo -e " Software dependencies:"
	echo -e "	- gdal-bin"
	echo -e "----------------------------------"
	echo -e ""
	echo -e " syntax: oft-sar-ALOS-KC-full <project_folder> <ISO3/AOI> <year>"
	echo -e ""
	echo -e " description of input parameters:"
	echo -e " project_folder	(output) pathname of the folder where the data will be stored (will create a subfolder ZIP with the downloaded files)"
 	echo -e " ISO3/AOI		ISO3 country code or shapefile of your area of interest"
	echo -e " Year			Acquisition Year (2007, 2008, 2009, 2010 or 2015)"
	echo -e " filtering		Apply Refined Lee Filter"
	echo -e "			  Available choices:"
	echo -e "			  0: no filtering applied"
	echo -e "			  1: filter applied"
	echo -e ""		

  	exit 1
else

	echo -e "-------------------------------------------------------------"
	echo -e " Open Foris SAR Toolkit, version ${OSK_VERSION}"
	echo -e " This scripts download ALOS K&C mosaics based on the extent" 
	echo -e "  of a given a given shapefile or a country boundary"
	echo -e "------------------------------------------------------------"
	echo -e ""

	# set up initial script variables
	mkdir -p $1
	OUT_DIR=`readlink -f $1` 

	ZIP_DIR=${OUT_DIR}/ZIP
	mkdir -p ${ZIP_DIR}
	YEAR=$3

	TMP_DIR=${OUT_DIR}/.TMP$3
	mkdir -p ${TMP_DIR}
	# source libs
	source ${OPENSARKIT}/lib/helpers_source
fi


#----------------------------------------------------------------------
# 2 check if AOI comes from country code or is already a shapefile


if [ `echo $2 | grep shp` ]; then # AOI case

	AOI=`readlink -f $2`
	AOI_PATH=`dirname ${AOI}`

	# check numberof layers/polygons
	aoi_valid_poly ${AOI} ${TMP_DIR}/aoi_convex.shp ${TMP_DIR} 

	#check EPSG
	if [ -e ${TMP_DIR}/aoi_convex.shp ];then
		aoi_valid_epsg ${TMP_DIR}/aoi_convex.shp ${TMP_DIR}/aoi_wgs84.shp ${TMP_DIR} 
	else	
		aoi_valid_epsg ${AOI} ${TMP_DIR}/aoi_wgs84.shp ${TMP_DIR} 
	fi
	if [ -e ${TMP_DIR}/aoi_wgs84.shp ];then
		mv ${TMP_DIR}/aoi_wgs84* ${AOI_PATH}
		AOI=${AOI_PATH}/aoi_wgs84.shp
	elif [ -e ${TMP_DIR}/aoi_convex.shp ];then
		mv ${TMP_DIR}/aoi_convex* ${AOI_PATH}
		AOI=${AOI_PATH}/aoi_convex.shp
	else 
		AOI=${AOI}
	fi
else # country case
	mkdir -p ${OUT_DIR}/AOI/
	aoi_from_iso3 $2 ${OUT_DIR}/AOI
	AOI=${OUT_DIR}/AOI/$2.shp
fi
echo $AOI > /home/avollrath/log_aoi
poft-sar-ALOS-KC-download ${OUT_DIR} ${AOI} ${YEAR} ${CRED_FILE}
oft-sar-ALOS-KC-process ${OUT_DIR} ${AOI} ${YEAR} $4