#! /bin/bash
# taken from  LOUIS MARASCIO at http://fitnr.com/showing-a-bash-spinner.html
spinner()
{
    local pid=$1
    local delay=0.75
    local spinstr='|\-/'
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        local temp=${spinstr#?}
        printf " [%c]  " "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done
    printf "    \b\b\b\b"
}


function check_tar()  {
	gunzip -c $1 2>&1 | tar t >> /dev/null 2>&1
  echo $?
}

function set_tmp_KC() {
  if [ -z "$1" ]; then
    echo " Missing arguments. Syntax:"
    echo " set_tmp_KC <Nr. of Tiles> "
    return
  fi

  if [ ! -e /ram ];then
    echo " Info: No RAM disk found at /ram for temporary file storage. Using harddisk instead."
    return
  fi

  echo -e " Info: Checking if RAM disk offers sufficient memory for temporary file storage ..."
  FREE_RAM=$(df | grep /ram | awk $'{print $2}')
  CPUS=`nproc`

  NEED_RAM1=`echo "$1 * 4000000" | bc`
  NEED_RAM2=`echo "$CPUS * 240000" | bc`

  NEED_RAM=`echo "${NEED_RAM1} + ${NEED_RAM2}" | bc`

  if [[ $( echo "${FREE_RAM_INT} > ${NEED_RAM}" | bc) -eq 1 ]];then
    mkdir -p /ram/KC_TMP
    export TMP_DIR=/ram/KC_TMP
    echo -e " Info: Using RAM disk at /ram/KC_TMP as TMP_Folder"
  else
    echo -e " Info: Not enough memory on RAM disk. Using standard temporary folder on harddisk."
  fi
}

function set_tmp_S1_RTC_bulk() {
  if [ -z "$2" ]; then
    echo " Missing arguments. Syntax:"
    echo " set_tmp_S1_RTC <Nr. of Frames> <resolution> "
    return
  fi

  if [ ! -e /ram ];then
    echo " Info: No RAM disk found at /ram for temporary file storage. Using harddisk instead."
    return
  fi

  echo -e " Info: Checking if RAM disk offers sufficient memory for temporary file storage ..."
  FREE_RAM=$(df | grep /ram | awk $'{print $2}')

  if [[ $2 == "MED_RES" ]];then
    NEED_RAM=`echo "$1 * 7450000" | bc`
  elif [[ $2 == "HI_RES" ]];then
    NEED_RAM=`echo "$1 * 7450000 * 9" | bc`
  fi

  if [[ $( echo "${FREE_RAM} > ${NEED_RAM}" | bc) -eq 1 ]];then
    mkdir -p /ram/SAR_TMP
    export TMP_DIR=/ram/SAR_TMP
    echo -e " Info: Using RAM disk at /ram/SAR_TMP as TMP_Folder"
  else
    echo -e " Info: Not enough memory on RAM disk. Using standard temporary folder on harddisk."
  fi
}


function set_tmp_S1_TS() {
  echo "here 1"
  if [ -z "$1" ]; then
    echo " Missing arguments. Syntax:"
    echo " set_tmp_S1_RTC <Size of Images> "
    return
  fi

  if [ ! -e /ram ];then
    echo " Info: No RAM disk found at /ram for temporary file storage. Using harddisk instead."
    return
  fi

  echo -e " Info: Checking if RAM disk offers sufficient memory for temporary file storage ..."
  FREE_RAM=$(df | grep /ram | awk $'{print $2}')
  STACK_SIZE=$(echo "$1 * 2.1" | bc)

  if [[ $( echo "${FREE_RAM} > ${STACK_SIZE}" | bc) -eq 1 ]];then
    mkdir -p /ram/SAR_TMP
    export TMP_DIR=/ram/SAR_TMP
    echo -e " Using RAM disk at /ram/SAR_TMP as TMP_Folder"
  else
    echo -e " Not enough memory on RAM disk. Using standard temporary folder on harddisk."
  fi

}

list_descendants ()
{
  local children=$(ps -o pid= --ppid "$1")

  for pid in $children
  do
    list_descendants "$pid"
  done

  echo "$children"
}
