#! /bin/bash

if [ "$#" != "3" ]; then  
	echo -e ""
	echo -e "----------------------------------"
	echo -e " Postprocessing script"
	echo -e " OpenSARKit, version ${VERSION}"
	echo -e " Developed by: Food and Agriculture Organization of the United Nations, Rome"
	echo -e " Author: ${AUTHOR}"
	echo -e " Contact: ${CONTACT}"
	echo -e "----------------------------------"
	echo -e ""
	echo -e " syntax: osk_w2w_mosaic <mosaic_folder> <DEM> <output_folder>"
	echo -e ""
	echo -e " input parameters:"
	echo -e " mosaic_folder		(input) folder where w2w mosaic files are stored (outcome of osk_w2w_mosaic)"
	echo -e " DEM			(input) Digital Elevation model, that covers the area of the w2w mosaics"
	echo -e " output_folder		(output) folder, where the output stack will be saved"
	echo -e ""
	echo -e "----------------------------------"
	echo -e " Software components:"
	echo -e "	- gdal-libraries"
	echo -e "	- SNAP Toolbox"
	echo -e "----------------------------------"
	exit 1
else
	echo -e ""
	echo -e "----------------------------------"
	echo -e " Postprocessing script"
	echo -e " OpenSARKit, version ${VERSION}"
	echo -e " Developed by: Food and Agriculture Organization of the United Nations, Rome"
	echo -e " Author: ${AUTHOR}"
	echo -e " Contact: ${CONTACT}"
	echo -e "----------------------------------"
	echo -e ""
	echo -e "----------------------------------"
	echo -e " Software components:"
	echo -e "	- gdal-libraries"
	echo -e "	- SNAP Toolbox"
	echo -e "----------------------------------"
	echo -e ""

	cd $1
	export PROC_DIR=`pwd`
	DEM=$2	
fi

TMP_DIR=${PROC_DIR}/TMP
mkdir -p ${TMP_DIR}
FINAL=$3
mkdir ${FINAL}


echo "-----------------------------------------------------------------------------------------------------------------"
echo " Calculate second order statistic Texture measurements (Dissimilarity, Homogeneity, GLCMVariance) for HH channel"
echo "-----------------------------------------------------------------------------------------------------------------"

# define path/name of output
INPUT_HH=${PROC_DIR}/Gamma0_HH_db.tif
INPUT_HV=${PROC_DIR}/Gamma0_HV_db.tif

OUTPUT_TEXTURE_HH=${TMP_DIR}/TEXTURE_HH.dim
OUTPUT_TEXTURE_HV=${TMP_DIR}/TEXTURE_HV.dim

bash $SNAP_EXE GLCM -PoutputASM='false' -PoutputContrast='false' -PoutputCorrelation='false' -PoutputEnergy='false' -PoutputEntropy='false' -PoutputMAX='false' -PoutputMean='false' -Ssource=${INPUT_HH} -t ${OUTPUT_TEXTURE_HH}

echo "-----------------------------------------------------------------------------------------------------------------"
echo " Calculate second order statistic Texture measurements (Dissimilarity, Homogeneity, GLCMVariance) for HV channel"
echo "-----------------------------------------------------------------------------------------------------------------"

bash $SNAP_EXE GLCM -PoutputASM='false' -PoutputContrast='false' -PoutputCorrelation='false' -PoutputEnergy='false' -PoutputEntropy='false' -PoutputMAX='false' -PoutputMean='false' -Ssource=${INPUT_HV} -t ${OUTPUT_TEXTURE_HV}

# get resolution of dataset
RES=`gdalinfo ${INPUT_HH} | grep "Pixel Size" | awk -F '(' '{print $2}' | awk -F ',' '{print $1}'`

# get the common area of DEM and outputfiles
XMIN=`osk_intersect_raster.py -a ${INPUT_HH} -b $DEM | awk -F ',' $'{print$1}' | cut -c 2-`
XMAX=`osk_intersect_raster.py -a ${INPUT_HH} -b $DEM | awk -F ',' $'{print$3}'`
YMAX=`osk_intersect_raster.py -a ${INPUT_HH} -b $DEM | awk -F ',' $'{print$2}'`
YMIN=`osk_intersect_raster.py -a ${INPUT_HH} -b $DEM | awk -F ',' $'{print$4}' | rev | cut -c 2-| rev`

gdalwarp -multi -wo NUM_THREADS=ALL_CPUS -of GTiff -t_srs EPSG:4326 -srcnodata 0 -dstnodata -9999 -te $XMIN $YMIN $XMAX $YMAX -tr ${RES} ${RES} ${INPUT_HH} ${FINAL}/01_Gamma0_HH_db.tif
gdalwarp -multi -wo NUM_THREADS=ALL_CPUS -of GTiff -t_srs EPSG:4326 -srcnodata 0 -dstnodata -9999 -te $XMIN $YMIN $XMAX $YMAX -tr ${RES} ${RES} ${INPUT_HV} ${FINAL}/02_Gamma0_HV_db.tif
gdalwarp -multi -wo NUM_THREADS=ALL_CPUS -of GTiff -t_srs EPSG:4326 -srcnodata 0 -dstnodata -9999 -te $XMIN $YMIN $XMAX $YMAX -tr ${RES} ${RES} ${PROC_DIR}/HH_HV_ratio.tif ${FINAL}/03_HH_HV_lin_ratio.tif
gdalwarp -multi -wo NUM_THREADS=ALL_CPUS -of GTiff -t_srs EPSG:4326 -srcnodata 0 -dstnodata -9999 -te $XMIN $YMIN $XMAX $YMAX -tr ${RES} ${RES} ${PROC_DIR}/HH_HV_db_ratio.tif ${FINAL}/04_HH_HV_db_ratio.tif
gdalwarp -multi -wo NUM_THREADS=ALL_CPUS -of GTiff -t_srs EPSG:4326 -srcnodata 0 -dstnodata -9999 -te $XMIN $YMIN $XMAX $YMAX -tr ${RES} ${RES} ${TMP_DIR}/TEXTURE_HH.data/band_1_Homogeneity.img ${FINAL}/05_Homogeneity_HH.tif
gdalwarp -multi -wo NUM_THREADS=ALL_CPUS -of GTiff -t_srs EPSG:4326 -srcnodata 0 -dstnodata -9999 -te $XMIN $YMIN $XMAX $YMAX -tr ${RES} ${RES} ${TMP_DIR}/TEXTURE_HH.data/band_1_GLCMVariance.img ${FINAL}/06_Variance_HH.tif
gdalwarp -multi -wo NUM_THREADS=ALL_CPUS -of GTiff -t_srs EPSG:4326 -srcnodata 0 -dstnodata -9999 -te $XMIN $YMIN $XMAX $YMAX -tr ${RES} ${RES} ${TMP_DIR}/TEXTURE_HH.data/band_1_Dissimilarity.img ${FINAL}/07_Dissimilarity_HH.tif
gdalwarp -multi -wo NUM_THREADS=ALL_CPUS -of GTiff -t_srs EPSG:4326 -srcnodata 0 -dstnodata -9999 -te $XMIN $YMIN $XMAX $YMAX -tr ${RES} ${RES} ${TMP_DIR}/TEXTURE_HV.data/band_1_Homogeneity.img ${FINAL}/08_Homogeneity_HV.tif
gdalwarp -multi -wo NUM_THREADS=ALL_CPUS -of GTiff -t_srs EPSG:4326 -srcnodata 0 -dstnodata -9999 -te $XMIN $YMIN $XMAX $YMAX -tr ${RES} ${RES} ${TMP_DIR}/TEXTURE_HV.data/band_1_GLCMVariance.img ${FINAL}/09_Variance_HV.tif
gdalwarp -multi -wo NUM_THREADS=ALL_CPUS -of GTiff -t_srs EPSG:4326 -srcnodata 0 -dstnodata -9999 -te $XMIN $YMIN $XMAX $YMAX -tr ${RES} ${RES} ${TMP_DIR}/TEXTURE_HV.data/band_1_Dissimilarity.img ${FINAL}/10_Dissimilarity_HV.tif
gdalwarp -multi -wo NUM_THREADS=ALL_CPUS -of GTiff -ot Float32 -t_srs EPSG:4326 -srcnodata -99999 -dstnodata -9999 -te $XMIN $YMIN $XMAX $YMAX -tr ${RES} ${RES} $DEM ${FINAL}/11_DEM_height.tif

# write world file (we will need for segmentation)
listgeo -tfw ${FINAL}/01_Gamma0_HH_db.tif
mv ${FINAL}/01_Gamma0_HH_db.tfw ${FINAL}/generic.tfw

# create slope and aspect layers
# mask for no data 
gdaldem slope -s 111120 ${FINAL}/11_DEM_height.tif ${FINAL}/12_DEM_slope.tif
gdaldem aspect ${FINAL}/11_DEM_height.tif ${FINAL}/13_DEM_aspect.tif

gdalbuildvrt -separate -srcnodata -9999 -vrtnodata -9999 ${FINAL}/stack.vrt ${FINAL}/*.tif
# remove temp files
rm -rf ${TMP_DIR}/ ${PROC_DIR}/target.d*

echo "----------------------------------"
echo " Processing succesfully finished"
echo "----------------------------------"
