#! /bin/bash

# mosaic Sentinel

#-------------------------------------------------------------------------------------------	
# 	0.1 Check for right usage & set up basic Script Variables
if [ "$#" != "2" ]; then
	
	echo -e ""
	echo -e "----------------------------------------------------------------------------------"
	echo -e " Open Foris SARKit, version ${OSK_VERSION}"
	echo -e " Preprocess Sentinel-1 GRD data from ESA Scihub"
	echo -e " Developed by: Food and Agriculture Organization of the United Nations, Rome"
	echo -e " Author: ${AUTHOR_1}"
	echo -e " Contact: ${CONTACT_1}"
	echo -e "----------------------------------------------------------------------------------"
	echo -e ""
	echo -e "----------------------------------------------------------------------------------"
	echo -e " Software dependencies:"
	echo -e "	- gdal-bin"
	echo -e "	- saga"
	echo -e "----------------------------------------------------------------------------------"
	echo -e ""
	echo -e " osk_S1_GRD_mosaic <project folder>  <match>"
	echo -e ""
	exit 1

else

	echo -e ""
	echo -e "----------------------------------------------------------------------------------"
	echo -e " Open Foris SARKit, version ${OSK_VERSION}"
	echo -e " Mosaic tool for merging S1 GRD gamma0 data"
	echo -e " Developed by: Food and Agriculture Organization of the United Nations, Rome"
	echo -e " Author: ${AUTHOR_1}"
	echo -e " Contact: ${CONTACT_1}"
	echo -e "----------------------------------------------------------------------------------"
	echo -e ""
	echo -e "----------------------------------------------------------------------------------"
	echo -e " Software dependencies:"
	echo -e "	- gdal-bin"
	echo -e "	- saga"
	echo -e "----------------------------------------------------------------------------------"
	echo -e ""

	cd $1
	PROC_DIR=`pwd`
	TMP_DIR=${PROC_DIR}/TMP
	mkdir -p ${TMP_DIR}
	OUT_DIR=${PROC_DIR}/MOSAIC
	mkdir -p ${OUT_DIR}
	MATCH=$2
fi

echo $PROC_DIR

for LINE in `ls -1 -d [0-2]*`;do

	cd $LINE
#	gdal_translate -of SAGA -a_nodata 0 01_Gamma0_VV.db.8bit.tif 01_Gamma0_VV.db.8bit.saga.sdat
#	gdal_translate -of SAGA -a_nodata 0 02_Gamma0_VH.db.8bit.tif 02_Gamma0_VH.db.8bit.saga.sdat
#	gdal_translate -of SAGA -a_nodata 0 03_VVVH_ratio.8bit.tif 03_VVVH_ratio.db.8bit.saga.sdat

	#VV channel
	#MEAN=`gdal_mean 01_Gamma0_VV.db.sdat`
	#SD=`gdal_stddev 01_Gamma0_VV.db.sdat`
	
	#saga_cmd grid_calculus 10 -INPUT:01_Gamma0_VV.db.sgrd -OUTPUT:01_Gamma0_VV.db.norm.sgrd -STRETCH 1
	#saga_cmd grid_calculus 10 -INPUT:02_Gamma0_VH.db.sgrd -OUTPUT:02_Gamma0_VH.db.norm.sgrd -STRETCH 1
#	saga_cmd grid_calculus 10 -INPUT:03_VVVH_ratio.sgrd -OUTPUT:03_VVVH_ratio.norm.sgrd -STRETCH 1

	#gdal_contrast_stretch -ndv '-99999' -outndv 0 -percentile-range 0.02 0.98 01_Gamma0_VV.db.norm.sdat 01_Gamma0_VV.db.8bit.norm.tif
	#gdal_contrast_stretch -ndv '-99999' -outndv 0 -percentile-range 0.02 0.98 02_Gamma0_VH.db.norm.sdat 02_Gamma0_VH.db.8bit.norm.tif
#	gdal_contrast_stretch -ndv '-99999' -outndv 0 -percentile-range 0.02 0.98 03_VVVH_ratio.norm.sdat 03_VVVH_ratio.8bit.norm.tif

	#gdal_translate -a_nodata 0 -of SAGA 01_Gamma0_VV.db.8bit.norm.tif 01_Gamma0_VV.db.8bit.norm.saga.sdat
	#gdal_translate -a_nodata 0 -of SAGA 02_Gamma0_VH.db.8bit.norm.tif 02_Gamma0_VH.db.8bit.norm.saga.sdat
#	gdal_translate -a_nodata 0 -of SAGA 03_VVVH_ratio.8bit.norm.tif 03_VVVH_ratio.8bit.norm.saga.sdat

	#saga_cmd grid_tools 15 -INPUT:01_Gamma0_VV.db.8bit.norm.saga.sgrd -RESULT:01_Gamma0_VV.db.8bit.norm.saga.replace.sgrd -METHOD:1 -MIN:0 -MAX65 -RNEW:0 -ROPERATOR:0 -RESULT_NODATA_VALUE:0
	#saga_cmd grid_tools 15 -INPUT:02_Gamma0_VH.db.8bit.norm.saga.sgrd -RESULT:02_Gamma0_VH.db.8bit.norm.saga.replace.sgrd -METHOD:1 -MIN:0 -MAX65 -RNEW:0 -ROPERATOR:0 -RESULT_NODATA_VALUE:0
	saga_cmd grid_tools 15 -INPUT:03_VVVH_ratio.8bit.norm.saga.sdat -RESULT:03_VVVH_ratio.8bit.norm.saga.replace.sdat -METHOD:1 -MIN:0 -MAX15 -RNEW:0 -ROPERATOR:0 -RESULT_NODATA_VALUE:0

#	saga_cmd grid_tools 11 -INPUT:01_Gamma0_VV.db.8bit.norm.saga.replace.sgrd -OUTPUT:01_Gamma0_VV.db.8bit.norm.saga.replace.final.sgrd -TYPE:1
	#saga_cmd grid_tools 11 -INPUT:02_Gamma0_VH.db.8bit.norm.saga.replace.sgrd -OUTPUT:02_Gamma0_VH.db.8bit.norm.saga.replace.final.sgrd -TYPE:1
	saga_cmd grid_tools 11 -INPUT:03_VVVH_ratio.8bit.norm.saga.replace.sdat -OUTPUT:03_VVVH_ratio.8bit.norm.saga.replace.final.sdat -TYPE:1
# replace values

# mosaic
	cd ../
done

LIST_VV=`ls */*VV.db.8bit.saga.sgrd | tr '\n' ';' | rev | cut -c 2- | rev`
LIST_VH=`ls */*VH.db.8bit.saga.sgrd | tr '\n' ';' | rev | cut -c 2- | rev`
LIST_VVVH=`ls */*ratio.db.8bit.saga.sgrd | tr '\n' ';' | rev | cut -c 2- | rev`

#saga_cmd -c=${CPU} grid_tools 3 -GRIDS:"20151218//01_Gamma0_VV.db.8bit.norm.saga.replace.final.sgrd;20151223//01_Gamma0_VV.db.8bit.norm.saga.replace.final.sgrd;20151213/01_Gamma0_VV.db.8bit.norm.saga.replace.final.sgrd" -TYPE:1 -OVERLAP:3 -BLEND_DIST:50 -MATCH:1 -TARGET_OUT_GRID:MOSAIC/01_GAMMA0_VV_mosaic_01.sgrd
#saga_cmd -c=${CPU} grid_tools 3 -GRIDS:"20151215/01_Gamma0_VV.db.8bit.norm.saga.replace.final.sgrd;20151220/01_Gamma0_VV.db.8bit.norm.saga.replace.final.sgrd" -TYPE:1 -OVERLAP:3 -BLEND_DIST:50 -MATCH:1 -TARGET_OUT_GRID:MOSAIC/01_GAMMA0_VV_mosaic_02.sgrd

#saga_cmd -c=${CPU} grid_tools 3 -GRIDS:"MOSAIC/01_GAMMA0_VV_mosaic_01.sgrd;MOSAIC/01_GAMMA0_VV_mosaic_02.sgrd" -TYPE:1 -OVERLAP:3 -BLEND_DIST:50 -MATCH:1 -TARGET_OUT_GRID:MOSAIC/01_GAMMA0_VV_mosaic_final.sgrd


#saga_cmd -c=${CPU} grid_tools 3 -GRIDS:"20151218//02_Gamma0_VH.db.8bit.norm.saga.replace.final.sgrd;20151223//02_Gamma0_VH.db.8bit.norm.saga.replace.final.sgrd;20151213/02_Gamma0_VH.db.8bit.norm.saga.replace.final.sgrd" -TYPE:1 -OVERLAP:3 -BLEND_DIST:50 -MATCH:1 -TARGET_OUT_GRID:MOSAIC/02_GAMMA0_VH_mosaic_01.sgrd
#saga_cmd -c=${CPU} grid_tools 3 -GRIDS:"20151215/02_Gamma0_VH.db.8bit.norm.saga.replace.final.sgrd;20151220/02_Gamma0_VH.db.8bit.norm.saga.replace.final.sgrd" -TYPE:1 -OVERLAP:3 -BLEND_DIST:50 -MATCH:1 -TARGET_OUT_GRID:MOSAIC/02_GAMMA0_VH_mosaic_02.sgrd

#saga_cmd -c=${CPU} grid_tools 3 -GRIDS:"MOSAIC/02_GAMMA0_VH_mosaic_01.sgrd;MOSAIC/02_GAMMA0_VH_mosaic_02.sgrd" -TYPE:1 -OVERLAP:3 -BLEND_DIST:50 -MATCH:1 -TARGET_OUT_GRID:MOSAIC/02_GAMMA0_VH_mosaic_final.sgrd

saga_cmd -c=${CPU} grid_tools 3 -GRIDS:"20151218/03_VVVH_ratio.8bit.norm.saga.replace.final.sgrd;20151223/03_VVVH_ratio.8bit.norm.saga.replace.final.sgrd;20151213/03_VVVH_ratio.8bit.norm.saga.replace.final.sgrd" -TYPE:1 -OVERLAP:3 -BLEND_DIST:50 -MATCH:1 -TARGET_OUT_GRID:MOSAIC/03_VVVH_mosaic_01.sgrd
saga_cmd -c=${CPU} grid_tools 3 -GRIDS:"20151215/03_VVVH_ratio.8bit.norm.saga.replace.final.sgrd;20151220/03_VVVH_ratio.8bit.norm.saga.replace.final.sgrd" -TYPE:1 -OVERLAP:3 -BLEND_DIST:50 -MATCH:1 -TARGET_OUT_GRID:MOSAIC/03_VVVH_mosaic_02.sgrd

saga_cmd -c=${CPU} grid_tools 3 -GRIDS:"MOSAIC/03_VVVH_mosaic_01.sgrd;MOSAIC/03_VVVH_mosaic_02.sgrd" -TYPE:1 -OVERLAP:3 -BLEND_DIST:50 -MATCH:1 -TARGET_OUT_GRID:MOSAIC/MOSAIC/03_VVVH_mosaic_final.sgrd


#saga_cmd -c=${CPU} grid_tools 3 -GRIDS:"${LIST_VV}" -TYPE:1 -OVERLAP:3 -BLEND_DIST:50 -MATCH:${MATCH} -TARGET_OUT_GRID:${OUT_DIR}/01_GAMMA0_VV_mosaic.sgrd
#saga_cmd -c=${CPU} grid_tools 3 -GRIDS:"${LIST_VH}" -TYPE:1 -OVERLAP:3 -BLEND_DIST:50 -MATCH:${MATCH} -TARGET_OUT_GRID:${OUT_DIR}/02_GAMMA0_VH_mosaic.sgrd
#saga_cmd -c=${CPU} grid_tools 3 -GRIDS:"${LIST_VVVH}" -TYPE:1 -OVERLAP:3 -BLEND_DIST:50 -MATCH:${MATCH} -TARGET_OUT_GRID:${OUT_DIR}/03_VVVH_mosaic.sgrd
