#! /bin/bash 

#-------------------------------------------------------------------------------------------	
# 	0.1 Check for right usage & set up basic Script Variables
if [ "$#" != "4" ]; then
	
	echo -e ""
	echo -e "----------------------------------------------------------------------------------"
	echo -e " Open Foris SARKit, version ${OSK_VERSION}"
	echo -e " Preprocess Sentinel-1 GRD data from ESA Scihub"
	echo -e " Developed by: Food and Agriculture Organization of the United Nations, Rome"
	echo -e " Author: ${AUTHOR_1}"
	echo -e " Contact: ${CONTACT_1}"
	echo -e "----------------------------------------------------------------------------------"
	echo -e ""
	echo -e "----------------------------------------------------------------------------------"
	echo -e " Software dependencies:"
	echo -e "	- ESA Sentinel Application Platform SNAP"
	echo -e "	- gdal-bin"
	echo -e "	- saga"
	echo -e "----------------------------------------------------------------------------------"
	echo -e ""
	echo -e " Usage: osk_S1_GRD_single_preprocess <filename> <output_folder> <mode> <filtering>" # <elevation> "
	echo -e ""
	echo -e " input parameters:"
	echo -e "  filename		(input) filename of the downloaded zip file"
	echo -e "  output_folder		(output) pathname of the output folder"
	echo -e "  mode			processing mode"
	echo -e "			  Available choices:"
	echo -e "			  HI_RES (10m output) "
	echo -e "			  MED_RES (30m output)"
	echo -e "  filtering		do additional Multi-Directional Filtering (recommended for single time "
	echo -e "			  Available choices:"
	echo -e "			   0: No additional filter applied"
	echo -e "			   1: additional filter applied"
#	echo -e "  elevation		(optional) filename to the digital elevation model"
#	echo -e ""
#	echo -e "  NOTE: The DEM file should be provided in Geotiff-format as a 16Bit Integer data type with 0 as the no data value."
	echo -e ""
	exit 1
else
	echo -e ""
	echo -e "----------------------------------------------------------------------------------"
	echo -e " Open Foris SARKit, version ${OSK_VERSION}"
	echo -e " Preprocess Sentinel-1 GRD data from ESA Scihub"
	echo -e " Developed by: Food and Agriculture Organization of the United Nations, Rome"
	echo -e " Author: ${AUTHOR_1}"
	echo -e " Contact: ${CONTACT_1}"
	echo -e "----------------------------------------------------------------------------------"
	echo -e ""
	echo -e "----------------------------------------------------------------------------------"
	echo -e " Software dependencies:"
	echo -e "	- ESA Sentinel Application Platform SNAP"
	echo -e "	- gdal-bin"
	echo -e "	- saga"
	echo -e "----------------------------------------------------------------------------------"
	echo -e ""

	# set up initial script variables
	FILE=`readlink -f $1`
	BASE=`basename ${FILE}`
	PROC_DIR=`dirname ${FILE}`
	TMP1=${PROC_DIR}/TMP/
	rm -rf ${TMP1}	
	mkdir -p ${TMP1}
	export TMP_DIR=${PROC_DIR}/TMP/${BASE}
	mkdir -p ${TMP_DIR}
	mkdir -p $2
	cd $2
	OUT_DIR=`pwd`

#	DEM_FILE=$2

	#
	source ${OPENSARKIT}/lib/helpers_source
fi


#-------------------------------------------------------------------------------------------
# 1 Get some scene infos and print them to Std.Out
#-------------------------------------------------------------------------------------------

#-------------------------------------------------------------------------------------------
# check input file
if [ `echo ${FILE} | rev | cut -c 1-3 | rev` == "dim" ];then

	echo "----------------------------------------------------------------"
	echo " Processing Scene: ${FILE}"
	echo "----------------------------------------------------------------"
else
	#-------------------------------------------------------------------------------------------
	# extract filenames
	SCENE_ID=`echo ${BASE} | rev | cut -c 5- | rev`
	DATE=${SCENE_ID:17:8}
	TRACK=${SCENE_ID:26:3}
	FRAME_START=${SCENE_ID:29:3}
	FRAME_END=${SCENE_ID:45:3}
	ORBIT=${SCENE_ID:49:6}
	MODE=${SCENE_ID:7:3}
	POL_MODE=${SCENE_ID:13:3}
	export SATELLITE="Sentinel-1"
	#-------------------------------------------------------------------------------------------

	echo "----------------------------------------------------------------"
	echo " Processing Scene: 		${SCENE_ID}"
	echo " Satellite/Sensor: 		${SATELLITE}"
	echo " Acquisiton Mode:		${MODE}"
	echo " Polarization Mode:		${POL_MODE}"
	echo " Acquisition Date (YYYYMMDD):	${DATE}"
	echo " Relative Satellite Track: 	${TRACK}"
	echo " Absolute Satellite Track: 	${ORBIT}"
	echo " Start Slice: 			${FRAME_START}"
	echo " End Slice: 			${FRAME_END}"
	echo "----------------------------------------------------------------"
fi
#-------------------------------------------------------------------------------------------
# 3 Preprocess imagery part I - Terrain Correction & Geocoding
#-------------------------------------------------------------------------------------------

#-------------------------------------------------------------------------------------------
# prepare DEM
#echo "create DEM crop"
#CROP_DEM=${TMP_DIR}/tmp_crop_dem.tif
#osk_crop_dem ${FILE} ${DEM_FILE} ${CROP_DEM}
#cd ${TMP_DIR}
#-------------------------------------------------------------------------------------------

#-------------------------------------------------------------------------------------------
# actual preprocessing according to the graphs
echo " Importing S1 GRD data file and apply the precise orbit file and calibrate the data to beta0"
bash ${SNAP_EXE} ${SNAP_GRAPHS}/S1_GRD_SDV_30_Orb_Noise_Brd_Cal.xml -x -Pinput=${FILE} -Poutput=${TMP_DIR}/CAL.dim

echo -ne " Remove border noise by deleting the outer 200 rows"
COLUMNS=`gdalinfo ${TMP_DIR}/CAL.data/Beta0_VV.img | grep "Size is" | awk '{print $3}' | sed s/,//g`
LINES=`gdalinfo ${TMP_DIR}/CAL.data/Beta0_VV.img | grep "Size is" | awk '{print $4}'`
NEW_WIDTH=`expr $COLUMNS - 1000`
NEW_HEIGHT=`expr $LINES - 1000`
bash ${SNAP_EXE} Subset -Pregion=500,500,$NEW_WIDTH,$NEW_HEIGHT -PcopyMetadata="true" -Ssource=${TMP_DIR}/CAL.dim -t ${TMP_DIR}/CAL_border.dim
rm -rf ${TMP_DIR}/CAL.d*

if [ $3 == "MED_RES" ];then
	echo " Applying the Terrain Flattening and multilook the data with a factor of 3"
	bash ${SNAP_EXE} ${SNAP_GRAPHS}/S1_GRD_SDV_30_TF_ML.xml -x -Pinput=${TMP_DIR}/CAL_border.dim -Poutput=${TMP_DIR}/TF.dim
	rm -rf ${TMP_DIR}/CAL_border.d*
	echo " Applying the Refined Lee Speckle Filter and doing the Geometric Terrain Correction (i.e. Geocoding)"
	bash ${SNAP_EXE} ${SNAP_GRAPHS}/S1_GRD_SDV_30_TC.xml -x -Pinput=${TMP_DIR}/TF.dim -Poutput=${TMP_DIR}/TF_TC.dim
	rm -rf ${TMP_DIR}/TF.d*
elif [ $3 == "HI_RES" ];then
	echo " Applying the Terrain Flattening and keep original resolution of 10m"
	bash ${SNAP_EXE} ${SNAP_GRAPHS}/S1_GRD_SDV_10_TF_ML.xml -x -Pinput=${TMP_DIR}/CAL_border.dim -Poutput=${TMP_DIR}/TF.dim
	rm -rf ${TMP_DIR}/CAL_border.d*
	echo " Applying the Refined Lee Speckle Filter and doing the Geometric Terrain Correction (i.e. Geocoding)"
	bash ${SNAP_EXE} ${SNAP_GRAPHS}/S1_GRD_SDV_10_SPK_TC.xml -x -Pinput=${TMP_DIR}/TF.dim -Poutput=${TMP_DIR}/TF_TC.dim
	rm -rf ${TMP_DIR}/TF.d*
fi

rm -rf ${PROC_DIR}/target*




