#! /bin/bash 

#-------------------------------------------------------------------------------------------	
# 	0.1 Check for right usage & set up basic Script Variables
if [ "$#" != "3" ]; then
	
	echo -e ""
	echo -e "----------------------------------"
	echo -e " OpenSARKit, version ${OSK_VERSION}"
	echo -e " Preprocess Sentinel-1 GRD data from ESA Scihub"
	echo -e " Developed by: Food and Agriculture Organization of the United Nations, Rome"
	echo -e " Author: ${AUTHOR_1}"
	echo -e " Contact: ${CONTACT_1}"
	echo -e "----------------------------------"
	echo -e ""
	echo -e "----------------------------------"
	echo -e "Software dependencies:"
	echo -e "	- ESA Sentinel Application Platform SNAP"
	echo -e "	- gdal-bin"
	echo -e "	- saga"
	echo -e "----------------------------------"
	echo -e ""
	echo -e "Usage: osk_S1_GRD_single_preprocess <filename> <elevation> <output_folder>"
	echo -e ""
	echo -e "input parameters:"
	echo -e " filename		(input) filename of the downloaded zip file"
	echo -e " elevation		(input) filename to the digital elevation model"
	echo -e ""
	echo -e " NOTE: The DEM file should be provided in Geotiff-format as a 16Bit Integer data type with 0 as the no data value."
	echo -e ""
	echo -e " output_folder		(output) pathname of the output folder"
	exit 1
else
	echo -e ""
	echo -e "----------------------------------"
	echo -e " OpenSARKit, version ${OSK_VERSION}"
	echo -e " Preprocess Sentinel-1 GRD data from ESA Scihub"
	echo -e " Developed by: Food and Agriculture Organization of the United Nations, Rome"
	echo -e " Author: ${AUTHOR_1}"
	echo -e " Contact: ${CONTACT_1}"
	echo -e "----------------------------------"
	echo -e ""
	echo -e "----------------------------------"
	echo -e " Software dependencies:"
	echo -e "	- ESA Sentinel Application Platform SNAP"
	echo -e "	- gdal-bin"
	echo -e "	- saga"
	echo -e "----------------------------------"
	echo -e ""

	# set up initial script variables
	FILE=`readlink -f $1`
	BASE=`basename ${FILE}`
	PROC_DIR=`dirname ${FILE}`
	TMP1=${PROC_DIR}/TMP/
	rm -rf ${TMP1}	
	mkdir -p ${TMP1}
	export TMP_DIR=${PROC_DIR}/TMP/${BASE}
	mkdir -p ${TMP_DIR}
	DEM_FILE=$2
	mkdir -p $3
	cd $3
	OUT_DIR=`pwd`

	#
	source ${OPENSARKIT}/lib/saga_helpers
	source ${OPENSARKIT}/lib/gdal_helpers
fi


#-------------------------------------------------------------------------------------------
# 1 Get some scene infos and print them to Std.Out
#-------------------------------------------------------------------------------------------

#-------------------------------------------------------------------------------------------
# check input file
if [ `echo ${FILE} | rev | cut -c 1-3 | rev` == "dim" ];then

	echo "----------------------------------------------------------------"
	echo " Processing Scene: ${FILE}"
	echo "----------------------------------------------------------------"
else
	#-------------------------------------------------------------------------------------------
	# extract filenames
	SCENE_ID=`echo ${BASE} | rev | cut -c 5- | rev`
	DATE=${SCENE_ID:17:8}
	TRACK=${SCENE_ID:26:3}
	FRAME_START=${SCENE_ID:29:3}
	FRAME_END=${SCENE_ID:45:3}
	ORBIT=${SCENE_ID:49:6}
	MODE=${SCENE_ID:7:3}
	POL_MODE=${SCENE_ID:13:3}
	export SATELLITE="Sentinel-1"
	#-------------------------------------------------------------------------------------------

	echo "----------------------------------------------------------------"
	echo " Processing Scene: 		${SCENE_ID}"
	echo " Satellite/Sensor: 		${SATELLITE}"
	echo " Acquisiton Mode:		${MODE}"
	echo " Polarization Mode:		${POL_MODE}"
	echo " Acquisition Date (YYYYMMDD):	${DATE}"
	echo " Relative Satellite Track: 	${TRACK}"
	echo " Absolute Satellite Track: 	${ORBIT}"
	echo " Start Slice: 			${FRAME_START}"
	echo " End Slice: 			${FRAME_END}"
	echo "----------------------------------------------------------------"
fi
#-------------------------------------------------------------------------------------------
# 3 Preprocess imagery part I - Terrain Correction & Geocoding
#-------------------------------------------------------------------------------------------

#-------------------------------------------------------------------------------------------
# prepare DEM
#echo "create DEM crop"
#CROP_DEM=${TMP_DIR}/tmp_crop_dem.tif
#osk_crop_dem ${FILE} ${DEM_FILE} ${CROP_DEM}
#cd ${TMP_DIR}
#-------------------------------------------------------------------------------------------

#-------------------------------------------------------------------------------------------
# actual preprocessing according to the graphs
echo " Importing S1 GRD data file and apply the precise orbit file, remove border noise and calibrate the data to beta0"
bash ${SNAP_EXE} ${SNAP_GRAPHS}/S1_GRD_SDV_30_Orb_Brd_Cal.xml -x -Pinput=${FILE} -Poutput=${TMP_DIR}/CAL.dim
echo " Applying the Terrain Flattening and multilook the data with a factor of 3"
bash ${SNAP_EXE} ${SNAP_GRAPHS}/S1_GRD_SDV_30_TF_ML.xml -x -Pinput=${TMP_DIR}/CAL.dim -Poutput=${TMP_DIR}/TF.dim
echo " Applying the Refined Lee Speckle Filter and doing the Geometric Terrain Correction (i.e. Geocoding)"
bash ${SNAP_EXE} ${SNAP_GRAPHS}/S1_GRD_SDV_30_SPK_TC.xml -x -Pinput=${TMP_DIR}/TF.dim -Poutput=${TMP_DIR}/TF_TC.dim

rm -rf ${PROC_DIR}/target*


if [ `echo ${FILE} | rev | cut -c 1-3 | rev` == "dim" ];then
	
	osk_md_filter ${TMP_DIR}/TF_TC.data/Gamma0_VV.img ${OUT_DIR}/Gamma0_VV.md-filtered.sdat SAGA 
	osk_md_filter ${TMP_DIR}/TF_TC.data/Gamma0_VH.img ${OUT_DIR}/Gamma0_VH.md-filtered.sdat SAGA

	saga_cmd -f=r -c=${CPU} grid_calculus 1 -GRIDS:${OUT_DIR}/Gamma0_VV.md-filtered.sgrd -XGRIDS:${OUT_DIR}/Gamma0_VH.md-filtered.sgrd -RESULT:${OUT_DIR}/VVVH_ratio.sgrd -FORMULA:"a / b"

	gdalbuildvrt -vrtnodata 0 -separate ${OUT_DIR}/RGB_${DATE}.vrt ${OUT_DIR}/Gamma0_VV.md-filtered.sdat ${OUT_DIR}/Gamma0_VH.md-filtered.sdat ${OUT_DIR}/VVVH_ratio.sdat

else

	#-------------------------------------------------------------------------------------------
	# set up final output directory
	FINAL_DIR=$OUT_DIR/${DATE}-${TRACK}
	mkdir -p ${FINAL_DIR}
	#-------------------------------------------------------------------------------------------
	osk_md_filter ${TMP_DIR}/TF_TC.data/Gamma0_VV.img ${FINAL_DIR}/Gamma0_VV.md-filtered.sdat SAGA
	osk_md_filter ${TMP_DIR}/TF_TC.data/Gamma0_VH.img ${FINAL_DIR}/Gamma0_VH.md-filtered.sdat SAGA

	saga_cmd -f=r -c=${CPU} grid_calculus 1 -GRIDS:${FINAL_DIR}/Gamma0_VV.md-filtered.sgrd -XGRIDS:${FINAL_DIR}/Gamma0_VH.md-filtered.sgrd -RESULT:${FINAL_DIR}/VVVH_ratio.sgrd -FORMULA:"a / b"

	gdalbuildvrt -vrtnodata -0 -separate ${FINAL_DIR}/RGB_${DATE}.vrt ${FINAL_DIR}/Gamma0_VV.md-filtered.sdat ${FINAL_DIR}/Gamma0_VH.md-filtered.sdat ${FINAL_DIR}/VVVH_ratio.sdat	

fi




