#! /bin/bash

# mosaic Sentinel

#-------------------------------------------------------------------------------------------	
# 	0.1 Check for right usage & set up basic Script Variables
if [ "$#" != "4" ]; then
	
	echo -e ""
	echo -e "----------------------------------------------------------------------------------"
	echo -e " Open Foris SARKit, version ${OSK_VERSION}"
	echo -e " Subsetting Sentinel-1 GRD data to a given Area of Interest - Bulk Mode"
	echo -e "----------------------------------------------------------------------------------"
	echo -e ""
	echo -e "----------------------------------------------------------------------------------"
	echo -e " Software dependencies:"
	echo -e "	- ESA Sentinel Application Platform SNAP"
	echo -e "	- gdal-bin"
	echo -e "----------------------------------------------------------------------------------"
	echo -e ""
	echo -e " osk_S1_GRD_bulk_subset <project folder> <AOI> <clean import> <delete zips>"
	echo -e ""
	exit 1

else
	echo -e ""
	echo -e "----------------------------------------------------------------------------------"
	echo -e " Open Foris SARKit, version ${OSK_VERSION}"
	echo -e " Subsetting Sentinel-1 GRD data to a given Area of Interest - Bulk Mode"
	echo -e "----------------------------------------------------------------------------------"
	echo -e ""


	# set up initial script variables	
	AOI=`readlink -f $2`
	cd $1
	PROC_DIR=`pwd`

	source ${OPENSARKIT}/lib/helpers_source
fi




for LINE in `ls -1 ${PROC_DIR}`;do
	
	cd ${LINE}

	for TRACK in `ls -1 ${PROC_DIR}/${LINE}`;do

		cd $TRACK

		for FILE in `ls -1 *zip`;do

			osk_S1_GRD_subset ${FILE} ${AOI} $3 $4

		done

		cd ../
	done

	cd ${PROC_DIR}
done


