#! /bin/bash 

#-------------------------------------------------------------------------------------------	
# 	0.1 Check for right usage & set up basic Script Variables
if [ "$#" != "3" ]; then
	
	echo -e ""
	echo -e "----------------------------------"
	echo -e " OpenSARKit, v.01"
	echo -e " Preprocess Sentinel-1 SLC data from ESA Scihub"
	echo -e " Developed by: Food and Agriculture Organization of the United Nations, Rome"
	echo -e " Author: Andreas Vollrath"
	echo -e " Contact: andreas.vollrath@fao.org"
	echo -e "----------------------------------"
	echo -e ""
	echo -e "----------------------------------"
	echo -e "Software dependencies:"
	echo -e "	- Sentinel 1 Toolbox (version 1.1.1)"
	echo -e "	- gdal-bin"
	echo -e "	- saga"
	echo -e "----------------------------------"
	echo -e ""
	echo -e "Usage: osk_single_S1_SLC_preprocess <filename> <elevation> <output_folder>"
	echo -e ""
	echo -e "input parameters:"
	echo -e " filename		(input) filename of the downloaded zip file"
	echo -e " elevation		(input) filename to the digital elevation model"
	echo -e ""
	echo -e " NOTE: The DEM file should be provided in Geotiff-format as a 16Bit Integer data type with 0 as the no data value."
	echo -e ""
	echo -e " output_folder		(output) pathname of the output folder"
	exit 1
else
	echo -e ""
	echo -e "----------------------------------"
	echo -e " OpenSARKit, v.01"
	echo -e " Preprocessing ALOS Level 1.5 scene from ASF server"
	echo -e " Developed by: Food and Agriculture Organization of the United Nations, Rome"
	echo -e " Author: Andreas Vollrath"
	echo -e " Contact: andreas.vollrath@fao.org"
	echo -e "----------------------------------"
	echo -e ""
	echo -e "----------------------------------"
	echo -e " Software dependencies:"
	echo -e "	- Sentinel 1 Toolbox (version 1.1.1)"
	echo -e "	- gdal-bin"
	echo -e "	- saga"
	echo -e "----------------------------------"
	echo -e ""

	# set up initial script variables
	FILE=`readlink -f $1`
	BASE=`basename ${FILE}`
	PROC_DIR=`dirname ${FILE}`
	TMP1=${PROC_DIR}/TMP/
	rm -rf ${TMP1}	
	mkdir -p ${TMP1}
	export TMP_DIR=${PROC_DIR}/TMP/${BASE}
	mkdir -p ${TMP_DIR}
	DEM_FILE=$2
	mkdir -p $3
	cd $3
	OUT_DIR=`pwd`
fi
#-------------------------------------------------------------------------------------------

#-------------------------------------------------------------------------------------------
# 1 Get some scene infos and print them to Std.Out
#-------------------------------------------------------------------------------------------

#-------------------------------------------------------------------------------------------
# extract filenames
echo $FILE
echo $BASE
SCENE_ID=`echo ${BASE} | rev | cut -c 5- | rev`
DATE=${SCENE_ID:17:8}
TRACK=${SCENE_ID:26:3}
FRAME_START=${SCENE_ID:29:3}
FRAME_END=${SCENE_ID:45:3}
ORBIT=${SCENE_ID:49:6}
MODE=${SCENE_ID:7:3}
POL_MODE=${SCENE_ID:13:3}
export SATELLITE="Sentinel-1"
#-------------------------------------------------------------------------------------------

echo "----------------------------------------------------------------"
echo "Processing Scene: 		${SCENE_ID}"
echo "Satellite/Sensor: 		${SATELLITE}"
echo "Acquisiton Mode:		${MODE}"
echo "Polarization Mode:		${POL_MODE}"
echo "Acquisition Date (YYYYMMDD):	${DATE}"
echo "Relative Satellite Track: 	${TRACK}"
echo "Absolute Satellite Track: 	${ORBIT}"
echo "Start Frame: 			${FRAME_START}"
echo "End Frame: 			${FRAME_END}"
echo "----------------------------------------------------------------"

#-------------------------------------------------------------------------------------------
# 3 Preprocess imagery part I - Terrain Correction & Geocoding
#-------------------------------------------------------------------------------------------

#-------------------------------------------------------------------------------------------
# define input/output file
INPUT_RAW=${FILE}	
OUTPUT_S1TBX=${TMP_DIR}/${SCENE_ID}
#-------------------------------------------------------------------------------------------

#-------------------------------------------------------------------------------------------
# set up final output directory
FINAL_DIR=$OUT_DIR/${TRACK}-${FRAME_START}-${ORBIT}
mkdir -p ${FINAL_DIR}
#-------------------------------------------------------------------------------------------

#-------------------------------------------------------------------------------------------
# prepare DEM
echo "create DEM crop"
CROP_DEM=${TMP_DIR}/tmp_crop_dem.tif
osk_crop_dem ${FILE} ${DEM_FILE} ${CROP_DEM}
cd ${TMP_DIR}
#-------------------------------------------------------------------------------------------

#-------------------------------------------------------------------------------------------
# actual preprocessing according to the graphs
echo "Importing S1 data file and update Orbit information with precise orbit files"
bash ${S1TBX_EXE} ${S1TBX_GRAPHS}/S1_import.xml -Pinput=${INPUT_RAW} -Pout_1=${TMP_DIR}/iw1.dim -Pout_2=${TMP_DIR}/iw2.dim -Pout_3=${TMP_DIR}/iw3.dim

echo "Calibrating, multi-looking and speckle-filtering of Swath IW1 - VV"
bash ${S1TBX_EXE} ${S1TBX_GRAPHS}/S1_preproc_VV.xml -Pinput=${TMP_DIR}/iw1.dim -Pout=${TMP_DIR}/iw1_preproc_vv.dim
echo "Calibrating, multi-looking and speckle-filtering of Swath IW2 - VV"
bash ${S1TBX_EXE} ${S1TBX_GRAPHS}/S1_preproc_VV.xml -Pinput=${TMP_DIR}/iw2.dim -Pout=${TMP_DIR}/iw2_preproc_vv.dim
echo "Calibrating, multi-looking and speckle-filtering of Swath IW3 - VV"
bash ${S1TBX_EXE} ${S1TBX_GRAPHS}/S1_preproc_VV.xml -Pinput=${TMP_DIR}/iw3.dim -Pout=${TMP_DIR}/iw3_preproc_vv.dim

echo "Terrain flattening and geometric terrain correction of Swath IW1 - VV"
bash ${S1TBX_EXE} ${S1TBX_GRAPHS}/S1_rtc.xml -Pinput=${TMP_DIR}/iw1_preproc_vv.dim -Pout=${TMP_DIR}/iw1_rtc_vv.dim
echo "Terrain flattening and geometric terrain correction of Swath IW2 - VV"
bash ${S1TBX_EXE} ${S1TBX_GRAPHS}/S1_rtc.xml -Pinput=${TMP_DIR}/iw2_preproc_vv.dim -Pout=${TMP_DIR}/iw2_rtc_vv.dim
echo "Terrain flattening and geometric terrain correction of Swath IW3 - VV"
bash ${S1TBX_EXE} ${S1TBX_GRAPHS}/S1_rtc.xml -Pinput=${TMP_DIR}/iw3_preproc_vv.dim -Pout=${TMP_DIR}/iw3_rtc_vv.dim

#echo "creating a Layover/Shadow mask for IW1"
#bash ${S1TBX_EXE} ${S1TBX_GRAPHS}/S1_layover_shadow_mask.xml -Pinput=${TMP_DIR}/iw1_preproc_vv.dim -Pout=${TMP_DIR}/layover_iw1.dim
#echo "creating a Layover/Shadow mask for IW2"
#bash ${S1TBX_EXE} ${S1TBX_GRAPHS}/S1_layover_shadow_mask.xml -Pinput=${TMP_DIR}/iw2_preproc_vv.dim -Pout=${TMP_DIR}/layover_iw2.dim
#echo "creating a Layover/Shadow mask for IW3"
#bash ${S1TBX_EXE} ${S1TBX_GRAPHS}/S1_layover_shadow_mask.xml -Pinput=${TMP_DIR}/iw3_preproc_vv.dim -Pout=${TMP_DIR}/layover_iw3.dim
#-------------------------------------------------------------------------------------------
#echo "Inverting Layover/Shadow Mask"	
###gdal_calc.py -A ${TMP_DIR}/layover.data/layover_mask.tif --outfile=${TMP_DIR}/mask.tif --calc="1*(A==1)" --NoDataValue=0
#-------------------------------------------------------------------------------------------

#-------------------------------------------------------------------------------------------
echo "Masking out Layover/Shadow regions"
gdalwarp -srcnodata 0 -dstnodata -99999 -of SAGA ${TMP_DIR}/iw1_rtc_vv.data/Gamma0_VV.img ${TMP_DIR}/tmp_vv_iw1_saga.sdat
gdalwarp -srcnodata 0 -dstnodata -99999 -of SAGA ${TMP_DIR}/iw2_rtc_vv.data/Gamma0_VV.img ${TMP_DIR}/tmp_vv_iw2_saga.sdat
gdalwarp -srcnodata 0 -dstnodata -99999 -of SAGA ${TMP_DIR}/iw3_rtc_vv.data/Gamma0_VV.img ${TMP_DIR}/tmp_vv_iw3_saga.sdat
#-------------------------------------------------------------------------------------------

#-------------------------------------------------------------------------------------------
echo "Filling small data holes by IDW interpolation"
saga_cmd -f=r grid_tools 25 -GRID:${TMP_DIR}/tmp_mask_vv_iw1_saga.sgrd -MAXGAPCELLS:250 -MAXPOINTS:500 -LOCALPOINTS:25 -CLOSED:${TMP_DIR}/tmp_mask_vv_iw1_filled.sgrd
saga_cmd -f=r grid_tools 25 -GRID:${TMP_DIR}/tmp_mask_vv_iw2_saga.sgrd -MAXGAPCELLS:250 -MAXPOINTS:500 -LOCALPOINTS:25 -CLOSED:${TMP_DIR}/tmp_mask_vv_iw2_filled.sgrd
saga_cmd -f=r grid_tools 25 -GRID:${TMP_DIR}/tmp_mask_vv_iw3_saga.sgrd -MAXGAPCELLS:250 -MAXPOINTS:500 -LOCALPOINTS:25 -CLOSED:${TMP_DIR}/tmp_mask_vv_iw3_filled.sgrd
#-------------------------------------------------------------------------------------------

#-------------------------------------------------------------------------------------------
echo "Applying multi-directional Lee-Filter for further smoothing"
saga_cmd -f=r grid_filter 3 -INPUT:${TMP_DIR}/tmp_mask_iw1_filled.sgrd -RESULT:${TMP_DIR}/tmp_mask_iw1_filtered.sgrd -NOISE_ABS:5000 -NOISE_REL:3000 -METHOD:1
saga_cmd -f=r grid_filter 3 -INPUT:${TMP_DIR}/tmp_mask_iw2_filled.sgrd -RESULT:${TMP_DIR}/tmp_mask_iw2_filtered.sgrd -NOISE_ABS:5000 -NOISE_REL:3000 -METHOD:1
saga_cmd -f=r grid_filter 3 -INPUT:${TMP_DIR}/tmp_mask_iw3_filled.sgrd -RESULT:${TMP_DIR}/tmp_mask_iw3_filtered.sgrd -NOISE_ABS:5000 -NOISE_REL:3000 -METHOD:1
#-------------------------------------------------------------------------------------------

#-------------------------------------------------------------------------------------------
echo "Create Final Output files"
gdalwarp -srcnodata -99999 -dstnodata 0 ${TMP_DIR}/tmp_mask_vv_iw1_filtered.sdat ${TMP_DIR}/Gamma0_VV_iw1.tif
gdalwarp -srcnodata -99999 -dstnodata 0 ${TMP_DIR}/tmp_mask_vv_iw2_filtered.sdat ${TMP_DIR}/Gamma0_VV_iw2.tif
gdalwarp -srcnodata -99999 -dstnodata 0 ${TMP_DIR}/tmp_mask_vv_iw3_filtered.sdat ${TMP_DIR}/Gamma0_VV_iw3.tif
#-------------------------------------------------------------------------------------------



if [ -e ${TMP_DIR}/iw1.data/i_IW1_VH.img ];then

	echo "Calibrating, multi-looking and speckle-filtering of Swath IW1 - VH"
	bash ${S1TBX_EXE} ${S1TBX_GRAPHS}/S1_preproc_VH.xml -Pinput=${TMP_DIR}/iw1.dim -Pout=${TMP_DIR}/iw1_preproc_vh.dim
	echo "Calibrating, multi-looking and speckle-filtering of Swath IW2 - VH"
	bash ${S1TBX_EXE} ${S1TBX_GRAPHS}/S1_preproc_VH.xml -Pinput=${TMP_DIR}/iw2.dim -Pout=${TMP_DIR}/iw2_preproc_vh.dim
	echo "Calibrating, multi-looking and speckle-filtering of Swath IW3 - VH"
	bash ${S1TBX_EXE} ${S1TBX_GRAPHS}/S1_preproc_VH.xml -Pinput=${TMP_DIR}/iw3.dim -Pout=${TMP_DIR}/iw3_preproc_vh_.dim

	echo "Terrain flattening and geometric terrain correction of Swath IW1 - VH"
	bash ${S1TBX_EXE} ${S1TBX_GRAPHS}/S1_rtc.xml -Pinput=${TMP_DIR}/iw1_preproc_vh.dim -Pout=${TMP_DIR}/iw1_rtc_vh.dim
	echo "Terrain flattening and geometric terrain correction of Swath IW2 - VH"
	bash ${S1TBX_EXE} ${S1TBX_GRAPHS}/S1_rtc.xml -Pinput=${TMP_DIR}/iw2_preproc_vh.dim -Pout=${TMP_DIR}/iw2_rtc_vh.dim
	echo "Terrain flattening and geometric terrain correction of Swath IW3 - VH"
	bash ${S1TBX_EXE} ${S1TBX_GRAPHS}/S1_rtc.xml -Pinput=${TMP_DIR}/iw3_preproc_vh.dim -Pout=${TMP_DIR}/iw3_rtc_vh.dim

fi	






echo "Merge IW Swaths"
#S1TBX1 ${S1TBX_GRAPHS}/S1_TOPS_merge.xml 

# rm -rf ${TMP_DIR}
