#! /bin/bash

#-------------------------------------------------------------------------------------------	
# 	0.1 Check for right usage & set up basic Script Variables
if [ "$#" != "3" ]; then
	
	echo -e ""
	echo -e "----------------------------------"
	echo -e " OpenSARKit, v.01"
	echo -e " Bulk preprocessing Sentinel-1 GRD data"
	echo -e " Developed by: Food and Agriculture Organization of the United Nations, Rome"
#	echo -e " Author: Andreas Vollrath"
#	echo -e " Contact: andreas.vollrath@fao.org"
	echo -e "----------------------------------"
	echo -e ""
	echo -e "----------------------------------"
	echo -e "Software dependencies:"
	echo -e "	- Sentinel 1 Toolbox (version 1.1.1)"
	echo -e "	- gdal-bin"
	echo -e "	- saga"
	echo -e "----------------------------------"
	echo -e ""
	echo -e "Usage: osk_S1_GRD_bulk_preprocess <input_folder> <elevation> <output_folder>"
	echo -e ""
	echo -e "input parameters:"
	echo -e " filename		(input) filename of the downloaded zip file"
	echo -e " elevation		(input) filename to the digital elevation model"
	echo -e ""
	echo -e " NOTE: The DEM file should be provided in Geotiff-format as a 16Bit Integer data type with 0 as the no data value."
	echo -e ""
	echo -e " output_folder		(output) pathname of the output folder"
	exit 1
else
	echo -e ""
	echo -e "----------------------------------"
	echo -e " OpenSARKit, v.01"
	echo -e " Bulk preprocessing Sentinel-1 GRD data"
	echo -e " Developed by: Food and Agriculture Organization of the United Nations, Rome"
#	echo -e " Author: Andreas Vollrath"
#	echo -e " Contact: andreas.vollrath@fao.org"
	echo -e "----------------------------------"
	echo -e ""
	echo -e "----------------------------------"
	echo -e " Software dependencies:"
	echo -e "	- Sentinel 1 Toolbox (version 1.1.1)"
	echo -e "	- gdal-bin"
	echo -e "	- saga"
	echo -e "----------------------------------"
	echo -e ""

	# set up initial script variables
	cd $1
	PROC_DIR=`pwd`
	TMP=${PROC_DIR}/TMP/
	export TMP_DIR=${PROC_DIR}/TMP/
	mkdir -p ${TMP_DIR}
	DEM_FILE=$2
	#mkdir -p $3
	#cd $3
	#OUT_DIR=`pwd`
fi


for LINE in `ls -1 ${PROC_DIR}`;do
	
	cd ${LINE}
	# list zip files
	
	if [ `ls -1 | wc -l` -eq 1 ];then

		SCENE=`ls` 
		echo "Processing Scene ${SCENE} "
		osk_S1_GRD_single_preprocess ${SCENE} ${DEM_FILE} .

	else

		ls -1 | tr '\n' ',' > $TMP_DIR/slicelist

		echo "Assembling the products of the same swath"
		bash ${S1TBX_EXE} ${S1TBX_GRAPHS}/S1_GRD_slice_assembly.xml -Pfilelist=`cat ${TMP_DIR}/slicelist` -Poutput=${TMP_DIR}/${LINE}.dim

		echo "Processing the swath image"
		osk_S1_GRD_single_preprocess ${TMP_DIR}/${LINE}.dim ${DEM_FILE} .
	fi

	mkdir -p ZIP
	mv *.zip ZIP
	rm -rf target*

	cd ../

done







