#! /bin/bash

# The MIT License (MIT)
# Copyright (c) 2016 Andreas Vollrath

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is furnished
# to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
# OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

#-------------------------------------------------------------------------------------------
# 	0.1 Check for right usage & set up basic Script Variables
if [ "$#" != "1" ]; then

	echo -e "------------------------------------------------------------------"
	echo -e " Open Foris SAR Toolkit, version ${OSK_VERSION}"
	echo -e " Create TRMM precipitation maps for Sentinel-1 acquisitions"
	echo -e "------------------------------------------------------------------"
	echo -e ""
	echo -e "----------------------------------"
	echo -e "Software dependencies:"
	echo -e "	- ESA Sentinel Application Platform SNAP"
	echo -e "	- gdal-bin"
	echo -e "----------------------------------"
	echo -e ""
	echo -e " Usage: oft-sar-S1-trmm <input directory> "
	echo -e ""
	echo -e " input parameters:"
	echo -e " input directory (input) higher-level directory of the downloaded zip file (i.e. DATA folder created by oft-sar-S1-download)"
  echo -e ""
	exit 1
else
	echo -e "------------------------------------------------------------------"
	echo -e " Open Foris SARKit, version ${OSK_VERSION}"
	echo -e " Create TRMM precipitation maps for Sentinel-1 acquisitions"
	echo -e "------------------------------------------------------------------"

	# set up initial script variables
	#cd $1
	#PROC_DIR=`pwd`
	PROC_DIR=$(readlink -f $1)
	TMP_DIR=${SAR_TMP:-$PROC_DIR/TMP}
	AOI="${PROC_DIR}/../.AOI/aoi*.shp"
	rm -rf ${TMP_DIR}/*
  mkdir -p ${TMP_DIR}

	if [[ ${TS_PROC} -gt 0 ]];then
		echo " WARNING: You are going to process the time-series/timescan products. Processing mode has therefore been set to TS mode preperation."
		PROC_MODE=1
	fi
	# source libs
	source ${OPENSARKIT}/lib/helpers_source

fi

read -r -p " Please type your NASA Earthdata username:" TRMM_UNAME
read -s -p " Please type your NASA Earthdata password:" TRMM_PW

## Authoriation part
# create an access fike
#if [ -ne ~/.netrc ];then # add a if loop for shiny usage
	touch ~/.netrc
	echo "machine urs.earthdata.nasa.gov login ${TRMM_UNAME} password ${TRMM_PW}" > ~/.netrc
	chmod 0600 ~/.netrc
#fi

for TRACK in `ls -1 -d ${PROC_DIR}/[0-9]*`;do

	if [[ ${NR_OF_TRACKS} -eq 1 ]];then
		echo " Info: Processing Track: `basename ${TRACK}`"
	else
		echo " Info: Processing Track: `basename ${TRACK}` ($j/${NR_OF_TRACKS}) "
	fi

	echo " Info: Entering Track: ${TRACK}"
	cd ${TRACK}

	NR_OF_ACQ=`ls -1 | wc -l`
	echo " Info: Found ${NR_OF_ACQ} acquisitions for this swath"

	# loop through acquisition dates
	for ACQ in `ls -d -1 201*`;do

		echo " Info: Entering ${ACQ}"
		cd ${ACQ}

		mkdir -p TRMM/TMP
		mkdir -p TRMM/LOG

		# get acquisition date
		ACQ_DATE=${ACQ:0:8}

		# get acquisition time
		ACQ_TIME=$(xml_grep PRODUCT_SCENE_RASTER_START_TIME ${ACQ}.RTC.dim --text_only | awk '{print $2}')
		trmm_download_s1 ${ACQ_DATE} ${ACQ_TIME} ./TRMM ${TRACK}/cropline.shp TRMM/TMP TRMM/LOG

		cd ../
	done

	cd ../
done

rm -f ~/.netrc
