#! /bin/bash 

#-------------------------------------------------------------------------------------------	
# 	0.1 Check for right usage & set up basic Script Variables
if [ "$#" != "3" ]; then
	
	echo -e ""
	echo -e "----------------------------------"
	echo -e " OpenSARKit, v.01"
	echo -e " Preprocess Sentinel-1 SLC data from ESA Scihub"
	echo -e " Developed by: Food and Agriculture Organization of the United Nations, Rome"
	echo -e " Author: Andreas Vollrath"
	echo -e " Contact: andreas.vollrath@fao.org"
	echo -e "----------------------------------"
	echo -e ""
	echo -e "----------------------------------"
	echo -e "Software dependencies:"
	echo -e "	- Sentinel 1 Toolbox (version 1.1.1)"
	echo -e "	- gdal-bin"
	echo -e "	- saga"
	echo -e "----------------------------------"
	echo -e ""
	echo -e "Usage: osk_single_S1_SLC_preprocess <filename> <elevation> <output_folder>"
	echo -e ""
	echo -e "input parameters:"
	echo -e " filename		(input) filename of the downloaded zip file"
	echo -e " elevation		(input) filename to the digital elevation model"
	echo -e ""
	echo -e " NOTE: The DEM file should be provided in Geotiff-format as a 16Bit Integer data type with 0 as the no data value."
	echo -e ""
	echo -e " output_folder		(output) pathname of the output folder"
	exit 1
else
	echo -e ""
	echo -e "----------------------------------"
	echo -e " OpenSARKit, v.01"
	echo -e " Preprocessing ALOS Level 1.5 scene from ASF server"
	echo -e " Developed by: Food and Agriculture Organization of the United Nations, Rome"
	echo -e " Author: Andreas Vollrath"
	echo -e " Contact: andreas.vollrath@fao.org"
	echo -e "----------------------------------"
	echo -e ""
	echo -e "----------------------------------"
	echo -e " Software dependencies:"
	echo -e "	- Sentinel 1 Toolbox (version 1.1.1)"
	echo -e "	- gdal-bin"
	echo -e "	- saga"
	echo -e "----------------------------------"
	echo -e ""

	# set up initial script variables
	FILE=`readlink -f $1`
	BASE=`basename ${FILE}`
	PROC_DIR=`dirname ${FILE}`
	TMP1=${PROC_DIR}/TMP/
	rm -rf ${TMP1}	
	mkdir -p ${TMP1}
	export TMP_DIR=${PROC_DIR}/TMP/${BASE}
	mkdir -p ${TMP_DIR}
	DEM_FILE=$2
	mkdir -p $3
	cd $3
	OUT_DIR=`pwd`
fi


#-------------------------------------------------------------------------------------------
# 1 Get some scene infos and print them to Std.Out
#-------------------------------------------------------------------------------------------

#-------------------------------------------------------------------------------------------
# extract filenames
echo $FILE
echo $BASE
SCENE_ID=`echo ${BASE} | rev | cut -c 5- | rev`
DATE=${SCENE_ID:17:8}
TRACK=${SCENE_ID:26:3}
FRAME_START=${SCENE_ID:29:3}
FRAME_END=${SCENE_ID:45:3}
ORBIT=${SCENE_ID:49:6}
MODE=${SCENE_ID:7:3}
POL_MODE=${SCENE_ID:13:3}
export SATELLITE="Sentinel-1"
#-------------------------------------------------------------------------------------------

echo "----------------------------------------------------------------"
echo "Processing Scene: 		${SCENE_ID}"
echo "Satellite/Sensor: 		${SATELLITE}"
echo "Acquisiton Mode:		${MODE}"
echo "Polarization Mode:		${POL_MODE}"
echo "Acquisition Date (YYYYMMDD):	${DATE}"
echo "Relative Satellite Track: 	${TRACK}"
echo "Absolute Satellite Track: 	${ORBIT}"
echo "Start Frame: 			${FRAME_START}"
echo "End Frame: 			${FRAME_END}"
echo "----------------------------------------------------------------"

#-------------------------------------------------------------------------------------------
# 3 Preprocess imagery part I - Terrain Correction & Geocoding
#-------------------------------------------------------------------------------------------

#-------------------------------------------------------------------------------------------
# define input/output file
INPUT_RAW=${FILE}	
OUTPUT_S1TBX=${TMP_DIR}/${SCENE_ID}
#-------------------------------------------------------------------------------------------

#-------------------------------------------------------------------------------------------
# set up final output directory
FINAL_DIR=$OUT_DIR/${TRACK}-${FRAME_START}-${ORBIT}
mkdir -p ${FINAL_DIR}
#-------------------------------------------------------------------------------------------

#-------------------------------------------------------------------------------------------
# prepare DEM
echo "create DEM crop"
CROP_DEM=${TMP_DIR}/tmp_crop_dem.tif
osk_crop_dem ${FILE} ${DEM_FILE} ${CROP_DEM}
cd ${TMP_DIR}
#-------------------------------------------------------------------------------------------

#-------------------------------------------------------------------------------------------
# actual preprocessing according to the graphs
echo "Importing S1 GRD data file and do the calibration (beta), multilooking (3x3) and terrain flattening (gamma)"
bash ${S1TBX_EXE} ${S1TBX_GRAPHS}/S1_GRD_SDV_30_import_CAL_ML_TF.xml -Pinput=${INPUT_RAW} -Poutput=${TMP_DIR}/TF.dim
echo "Speckle Filtering and Geometric Terrain Correction (i.e. Geocoding)"
bash ${S1TBX_EXE} ${S1TBX_GRAPHS}/S1_GRD_SDV_30_SPK_TC.xml -Pinput=${TMP_DIR}/TF.dim -Poutput=${TMP_DIR}/TF_TC.dim











