#! /bin/bash

# crop DEM for scene size

#----------------------------------------------------------------------
#	0 Set up Script variables
#----------------------------------------------------------------------

# 	0.1 Check for right usage
if [ "$#" != "3" ]; then

	echo -e ""
	echo -e "----------------------------------"
	echo -e " OpenSARKit, v.01"
	echo -e " Crop DEM to Scene"
	echo -e " Developed by: Food and Agriculture Organization of the United Nations, Rome"
	echo -e " Author: Andreas Vollrath"
	echo -e " Contact: andreas.vollrath@fao.org"
	echo -e "----------------------------------"
	echo -e ""
	echo -e "----------------------------------"
	echo -e "Software dependencies:"
	echo -e "	- gdal-bin"
	echo -e "	- xml-twig-tools"
	echo -e "----------------------------------"
	echo -e ""
	echo -e "Syntax: osk_crop_dem <zip-file> <dem> <dem-crop>"
	echo -e ""
	echo -e " description of input parameters:"
	echo -e " zip-file		(input) downloaded zip file of the SAR scene"
	echo -e " elevation		(input) filename to the digital elevation model"
	echo -e " dem-crop		(output) cropped DEM file"
	echo -e ""
  exit 1
else
  FILE=`readlink -f $1`
  BASE=`basename ${FILE}`
  PROC_DIR=`dirname ${FILE}`
  cd ${PROC_DIR}	
  echo -e " Crop DEM to Scene"
fi

#----------------------------------------------------------------------------
# 1 check for sensor
if [ ${SATELLITE} == ALOS ];then

	SCENE_ID=`echo ${BASE} | rev | cut -c 5- | rev`
	echo $BASE
	echo $SCENE_ID
	unzip -q -j "${FILE}" "${SCENE_ID}/workreport" -d ${TMP_DIR}

	cd ${PROC_DIR}
	UL_LAT=`cat ${TMP_DIR}/workreport | grep Brs_ImageSceneLeftTopLatitude | awk -F"\=" $'{print $2}' | sed 's|"||g'`
	UL_LON=`cat ${TMP_DIR}/workreport | grep Brs_ImageSceneLeftTopLongitude | awk -F"\=" $'{print $2}' | sed 's|"||g'`
	LR_LAT=`cat ${TMP_DIR}/workreport | grep Brs_ImageSceneRightBottomLatitude | awk -F"\=" $'{print $2}' | sed 's|"||g'`
	LR_LON=`cat ${TMP_DIR}/workreport | grep Brs_ImageSceneRightBottomLongitude | awk -F"\=" $'{print $2}' | sed 's|"||g'`
	UR_LAT=`cat ${TMP_DIR}/workreport | grep Brs_ImageSceneRightTopLatitude | awk -F"\=" $'{print $2}' | sed 's|"||g'`
	UR_LON=`cat ${TMP_DIR}/workreport | grep Brs_ImageSceneRightTopLongitude | awk -F"\=" $'{print $2}' | sed 's|"||g'`
	LL_LAT=`cat ${TMP_DIR}/workreport | grep Brs_ImageSceneLeftBottomLatitude | awk -F"\=" $'{print $2}' | sed 's|"||g'`
	LL_LON=`cat ${TMP_DIR}/workreport | grep Brs_ImageSceneLeftBottomLongitude | awk -F"\=" $'{print $2}' | sed 's|"||g'`

elif [ ${SATELLITE} == "Sentinel-1" ];then

	BASE=`basename ${FILE}`
	SCENE_ID=`echo ${BASE} | rev | cut -c 5- | rev`
	unzip -q -j "${FILE}" "${SCENE_ID}.SAFE/preview/map-overlay.kml" -d ${TMP_DIR}

	LR_LON=`cat map-overlay.kml | xml_grep coordinates --text_only | awk -F"\ " $'{print $1}' | awk -F"\,"  $'{print $1}'`
	LR_LAT=`cat map-overlay.kml | xml_grep coordinates --text_only | awk -F"\ " $'{print $1}' | awk -F"\,"  $'{print $2}'`
	LL_LON=`cat map-overlay.kml | xml_grep coordinates --text_only | awk -F"\ " $'{print $2}'| awk -F"\,"  $'{print $1}'` 
	LL_LAT=`cat map-overlay.kml | xml_grep coordinates --text_only | awk -F"\ " $'{print $2}' | awk -F"\,"  $'{print $2}'`
 	UL_LON=`cat map-overlay.kml | xml_grep coordinates --text_only | awk -F"\ " $'{print $3}' | awk -F"\,"  $'{print $1}'` 
	UL_LAT=`cat map-overlay.kml | xml_grep coordinates --text_only | awk -F"\ " $'{print $3}' | awk -F"\,"  $'{print $2}'`
 	UR_LON=`cat map-overlay.kml | xml_grep coordinates --text_only | awk -F"\ " $'{print $4}' | awk -F"\,"  $'{print $1}'` 
	UR_LAT=`cat map-overlay.kml | xml_grep coordinates --text_only | awk -F"\ " $'{print $4}' | awk -F"\,"  $'{print $2}'`
fi	
#----------------------------------------------------------------------------


#----------------------------------------------------------------------------
# check if ascending or descending and add buffer zone
if [ `echo " $LR_LON < $UR_LON" | bc` -eq 1 ];then

	LL_LON_BUF=`echo "${LL_LON} - 0.175" | bc`
	UL_LAT_BUF=`echo "${UL_LAT} + 0.175" | bc`
	UR_LON_BUF=`echo "${UR_LON} + 0.175" | bc`
	LR_LAT_BUF=`echo "${LR_LAT} - 0.175" | bc`

	# Export DEM	
	gdal_translate -of GTiff -a_nodata -0 -projwin ${LL_LON_BUF} ${UL_LAT_BUF} ${UR_LON_BUF} ${LR_LAT_BUF} $2 $3 

else

	LR_LON_BUF=`echo "${LR_LON} + 0.175" | bc`
	UR_LAT_BUF=`echo "${UR_LAT} + 0.175" | bc`
	UL_LON_BUF=`echo "${UL_LON} - 0.175" | bc`
	LL_LAT_BUF=`echo "${LL_LAT} - 0.175" | bc`

	# Export DEM
	gdal_translate -of GTiff -a_nodata -0 -projwin ${UL_LON_BUF} ${UR_LAT_BUF} ${LR_LON_BUF} ${LL_LAT_BUF} $2 $3 

fi
#----------------------------------------------------------------------------

