#! /bin/bash

# dependecies
#	SAGA GIS (Version > 2.1.4)
#  dans-gdal-scripts
#  gdal-libs


#----------------------------------------------------------------------
#	0 Set up Script variables
#----------------------------------------------------------------------

#-------------------------------------------------------------------------------------------	
# 	0.1 Check for right usage & set up basic Script Variables
if [ "$#" != "2" ]; then

	echo -e ""
	echo -e "----------------------------------"
	echo -e " OpenSARKit, v.01"
	echo -e " Mosaic preprocessed scenes to the full path extents "
	echo -e " written by: Andreas Vollrath, UN-FAO, Rome"
	echo -e "----------------------------------"
	echo -e ""
	echo -e "----------------------------------"
	echo -e " Software dependencies:"
	echo -e "	- SAGA GIS"
	echo -e "	- dans-gdal-scripts"
	echo -e "	- gdal"
	echo -e "----------------------------------"
	echo -e ""
	echo -e " syntax: osk_merge_path_ALOS <path_to_tracks> <output_resolution>"
	echo -e ""
	echo -e " description of input parameters:"
	echo -e " path_to_tracks		pathname, where the preprocessed scenes are sorted by acquisition date"
	echo -e ""
	echo -e " NOTE: This script should be followed by osk_bulk_preproc_ALOS_ASF_L1.5"
	echo -e ""
	echo -e " resolution		output resolution in degree ( - for original resolution)"
	echo -e ""
  exit 1
else
	echo -e ""
	echo -e "----------------------------------"
	echo -e " OpenSARKit, v.01"
	echo -e " Mosaic preprocessed scenes to the full path extents "
	echo -e " written by: Andreas Vollrath, UN-FAO, Rome"
	echo -e "----------------------------------"
	echo -e ""
	echo -e "----------------------------------"
	echo -e " Software dependencies:"
	echo -e "	- SAGA GIS"
	echo -e "	- dans-gdal-scripts"
	echo -e "	- gdal"
	echo -e "----------------------------------"
	echo -e ""

# set up input data
	cd $1
	export PROC_DIR=`pwd`
fi

# Number of CPUs (for SAGA GIS)
CPU=`lscpu | grep "CPU(s):" | awk $'{print $2}' | head -1`

# Path structure
cd ${PROC_DIR}
TMP_DIR=${PROC_DIR}/TMP
mkdir -p ${TMP_DIR}
mkdir -p ${PROC_DIR}/PATH
mkdir -p ${PROC_DIR}/PATH/MOSAICS
mkdir -p ${PROC_DIR}/PATH/KMZS
mkdir -p ${PROC_DIR}/PATH/OUTLINES

# Loop for Acquisition Date
for ACQ_DATE in `ls -1 -d [1,2]*`;do 

	cd ${ACQ_DATE}

	# Loop for Frames
	for FRAME in `ls -1 -d [0-9]*`;do 
		

		cd $FRAME
		ORBIT=${FRAME:5:10}
	
		if [ $2 == "-" ];then
	
			echo "Translate to SAGA GIS format (powerful and fast raster manipulation)"				
	#		gdalwarp -multi -wo NUM_THREADS=ALL_CPUS -t_srs EPSG:4326 -tr 0.000138889 0.000138889 -overwrite -of SAGA -srcnodata "0" -dstnodata "-99999" Gamma0_HH.tif ${TMP_DIR}/${FRAME}"_Gamma0_HH_saga.sdat"
	#		gdalwarp -multi -wo NUM_THREADS=ALL_CPUS -t_srs EPSG:4326 -tr 0.000138889 0.000138889 -overwrite -of SAGA -srcnodata "0" -dstnodata "-99999" Gamma0_HV.tif ${TMP_DIR}/${FRAME}"_Gamma0_HV_saga.sdat"
	
			gdalwarp -multi -wo NUM_THREADS=ALL_CPUS -t_srs EPSG:4326 -overwrite -of SAGA -srcnodata "0" -dstnodata "-99999" Gamma0_HH.tif ${TMP_DIR}/${FRAME}"_Gamma0_HH_saga.sdat"
			gdalwarp -multi -wo NUM_THREADS=ALL_CPUS -t_srs EPSG:4326 -overwrite -of SAGA -srcnodata "0" -dstnodata "-99999" Gamma0_HV.tif ${TMP_DIR}/${FRAME}"_Gamma0_HV_saga.sdat"

			echo ${TMP_DIR}/${FRAME}"_Gamma0_HH_saga.sgrd" >> ${TMP_DIR}/Gamma0_HH_list
			echo ${TMP_DIR}/${FRAME}"_Gamma0_HV_saga.sgrd" >> ${TMP_DIR}/Gamma0_HV_list
		
			cd ../

		else

			RES=$2
			
			echo "Translate to SAGA GIS format (powerful and fast raster manipulation)"				
			gdalwarp -multi -wo NUM_THREADS=ALL_CPUS -t_srs EPSG:4326 -tr ${RES} ${RES} -overwrite -of SAGA -srcnodata "0" -dstnodata "-99999" Gamma0_HH.tif ${TMP_DIR}/${FRAME}"_Gamma0_HH_saga.sdat"
			gdalwarp -multi -wo NUM_THREADS=ALL_CPUS -t_srs EPSG:4326 -tr ${RES} ${RES} -overwrite -of SAGA -srcnodata "0" -dstnodata "-99999" Gamma0_HV.tif ${TMP_DIR}/${FRAME}"_Gamma0_HV_saga.sdat"

			echo ${TMP_DIR}/${FRAME}"_Gamma0_HH_saga.sgrd" >> ${TMP_DIR}/Gamma0_HH_list
			echo ${TMP_DIR}/${FRAME}"_Gamma0_HV_saga.sgrd" >> ${TMP_DIR}/Gamma0_HV_list
	
			cd ../

		fi

	
	done

	echo "Merge Paths for HH Polarization"
	LIST_HH=`cat ${TMP_DIR}/Gamma0_HH_list | tr '\n' ';' | rev | cut -c 2- | rev`
	saga_cmd -c=${CPU} grid_tools 3 -GRIDS:"${LIST_HH}" -TYPE:7 -OVERLAP:4 -BLEND_DIST:0 -TARGET_OUT_GRID:${PROC_DIR}/PATH/MOSAICS/${ACQ_DATE}"_Gamma0_HH_"${ORBIT}.sgrd

	echo "Merge Paths for HV Polarization"
	LIST_HV=`cat ${TMP_DIR}/Gamma0_HV_list | tr '\n' ';' | rev | cut -c 2- | rev`
	saga_cmd -c=${CPU} grid_tools 3 -GRIDS:"${LIST_HV}" -TYPE:7 -OVERLAP:4 -BLEND_DIST:0 -TARGET_OUT_GRID:${PROC_DIR}/PATH/MOSAICS/${ACQ_DATE}"_Gamma0_HV_"${ORBIT}.sgrd
	
	echo "creating a shapefile for all valid points"
	gdal_trace_outline ${PROC_DIR}/PATH/MOSAICS/${ACQ_DATE}"_Gamma0_HV_"${ORBIT}.sdat -ndv -99999 -dp-toler 0 -out-cs en -ogr-out ${PROC_DIR}/PATH/OUTLINES/${ACQ_DATE}"_Gamma0_HV_"${ORBIT}.shp
	echo "creating a KMZ file for GoogleEarth"
	gdal_translate -of KMLSUPEROVERLAY -a_nodata 0 -outsize 25% 25% -scale 0.001 0.1 0 255 ${PROC_DIR}/PATH/MOSAICS/${ACQ_DATE}"_Gamma0_HV_"${ORBIT}.sdat  ${PROC_DIR}/PATH/KMZS/${ACQ_DATE}"_Gamma0_HV_"${ORBIT}.kmz -co FORMAT=PNG

	rm -rf ${TMP_DIR}/*
	cd ${PROC_DIR}
	
done

cd ${PROC_DIR}

tar -cfzv ${PROC_DIR}/PATH/Outlines.tar.gz ${PROC_DIR}/PATH/OUTLINES
tar -cfzv ${PROC_DIR}/PATH/KMZS.tar.gz ${PROC_DIR}/PATH/KMZS
rm -rf ${TMP_DIR}


