#-----------------------------------------------------------------------------
# Multi-sensor fusion
tabItem(tabName = "ms_ls_s1_kc_srtm",
        fluidRow(
          # Include the line below in ui.R so you can send messages
          tags$head(tags$script(HTML('Shiny.addCustomMessageHandler("jsCode",function(message) {eval(message.value);});'))),
          
          # for busy indicator 
          useShinyjs(),
          tags$style(appCSS),
          
          #----------------------------------------------------------------------------------
          # Processing Panel Sentinel-1
          box(
            
            # Title                     
            title = "Processing Panel", status = "success", solidHeader= TRUE,
            tags$h4("Multi-Sensor Fusion for optical, Sentinel-1, ALOS K&C mosaics and SRTM DEM."),
            hr(),
            tags$b("Short description"),
            p("This module will create a new image stack including all bands from the different data sets. The optical data will behave as a master, defining 
               extent and resolution of the final multi-sensor stack."),
            hr(),
            tags$b("Optical data stack (master, i.e. extent and resolution will be defined by this layer):"),
            p("The path should point to the VRT file of Landsat data generated on SEPAL, i.e. \"/download/mosaic_title/mosaic_title.vrt\""),
            shinyFilesButton("ms2_lsat_file","Browse","Browse",FALSE),br(),br(),
            verbatimTextOutput("ms2_lsat_file"),hr(),
            
            tags$b("Add optical band indices: (does only work with Sepal generated data stacks.)"),
            p("This option allows to calculate additional Band Indices (i.e. NDVI, MSAVI, NDMI, NBR) from the Landsat stack and add them to the multi-sensor stack."),
            radioButtons("ms_ls_s1_kc_srtm_lsatind", "",
                         c("Yes" = "1",
                           "No" = "0")),hr(),
            
            tags$b("Optional: Sentinel-1 stack (Timescan stack from OST):"),
            p("The path should point to the VRT file of the Sentinel-1 Timescan stack generated by OST"),
            shinyFilesButton("ms2_s1_file","Browse","Browse",FALSE),br(),br(),
            verbatimTextOutput("ms2_s1_file"),hr(),
            
            tags$b("Optional: ALOS K&C stack (RGB composite):"),
            p("The path should point to the VRT file of the ALOS K&C RGB stack generated by OST"),
            shinyFilesButton("ms2_alos_file","Browse","Browse",FALSE),br(),br(),
            verbatimTextOutput("ms2_alos_file"),hr(),
            
            tags$b("Optional: SRTM stack (height, slope, aspect):"),
            p("The path should point to the VRT file of the SRTM stack generated by OST"),
            shinyFilesButton("ms2_srtm_file","Browse","Browse",FALSE),br(),br(),
            verbatimTextOutput("ms2_srtm_file"),hr(),
            
            tags$b("Output directory:"),
            p("Select a folder where the output data files will be written to:"),
            shinyDirButton("ms_ls_s1_kc_srtm_outdir","Browse","Browse",FALSE),br(),br(),
            verbatimTextOutput("ms_ls_s1_kc_srtm_outdir"),hr(),
            #---------------------------------------------------------------------------
            
            #-----------------------------------------------------------------------------------------------------------------------------------
            # Trigger / Abort
            div(style="display: inline-block;vertical-align:top; width: 135px;",withBusyIndicatorUI(
              actionButton("ms_ls_s1_kc_srtm_pro_btn", "Start processing"))),
            div(style="display: inline-block;vertical-align:top; width: 125px;", withBusyIndicatorUI(
              actionButton("ms_ls_s1_kc_srtm_abort_btn", "Abort processing")
            )),
            #"Output:",
            textOutput("processMS_ls_s1_kc_srtm")
          ), #close box
          
          #-----------------------------------------------------------------------------------------------------------------------------------
          #   #----------------------------------------------------------------------------------
          #   # Info Panel
          box(
            title = "Info Panel", status = "success", solidHeader= TRUE,
            
            tabBox(width = 700,
                   tabPanel("Progress Monitor",
                            tags$h4("Monitor the progress of a running process"),hr(),
                            verbatimTextOutput("ms_ls_s1_kc_srtm_progress"))
            )
          ) # close box
            
      )
)