#-----------------------------------------------------------------------------
# Multi-sensor fusion
tabItem(tabName = "ms_ls_s1_kc",
        fluidRow(
          # Include the line below in ui.R so you can send messages
          tags$head(tags$script(HTML('Shiny.addCustomMessageHandler("jsCode",function(message) {eval(message.value);});'))),
          
          # for busy indicator 
          useShinyjs(),
          tags$style(appCSS),
          
          #----------------------------------------------------------------------------------
          # Processing Panel Sentinel-1
          box(
            
            # Title                     
            title = "Processing Panel", status = "success", solidHeader= TRUE,
            tags$h4("Multi-Sensor Fusion for Landsat, Sentnel-1 and ALOS K&C mosaics"),
            hr(),
            tags$b("Short description"),
            p("This module will create a new image stack including all bands "),
            hr(),
            tags$b("Landsat stack (best pixel mosaic from SEPAL):"),
            p("The path should point to the VRT file of Landsat data generated on SEPAL, i.e. \"/download/mosaic_title/mosaic_title.vrt\""),
            shinyFilesButton("ms1_lsat_file","Browse","Browse",FALSE),br(),br(),
            verbatimTextOutput("ms1_lsat_file"),hr(),
            
            tags$b("Add Landsat Band indices:"),
            p("This option allows to calculate additional Band Indices (i.e. NDVI, MSAVI, NDMI, NBR) from the Landsat stack and add them to the multi-sensor stack."),
            radioButtons("ms_ls_s1_kc_lsatind", "",
                         c("Yes" = "1",
                           "No" = "0")),hr(),
            
            tags$b("Sentinel-1 stack (Timescan stack from OST):"),
            p("The path should point to the VRT file of the Sentinel-1 Timescan stack generated by OST"),
            shinyFilesButton("ms1_s1_file","Browse","Browse",FALSE),br(),br(),
            verbatimTextOutput("ms1_s1_file"),hr(),
            
            tags$b("ALOS K&C stack (RGB composite):"),
            p("The path should point to the VRT file of the ALOS K&C RGB stack generated by OST"),
            shinyFilesButton("ms1_alos_file","Browse","Browse",FALSE),br(),br(),
            verbatimTextOutput("ms1_alos_file"),hr(),
            
            tags$b("Output directory:"),
            p("Select a folder where the output data files will be written to:"),
            shinyDirButton("ms_ls_s1_kc_outdir","Browse","Browse",FALSE),br(),br(),
            verbatimTextOutput("ms_ls_s1_kc_outdir"),hr(),
            #---------------------------------------------------------------------------
            
            #-----------------------------------------------------------------------------------------------------------------------------------
            # Trigger / Abort
            div(style="display: inline-block;vertical-align:top; width: 135px;",withBusyIndicatorUI(
              actionButton("ms_ls_s1_kc_pro_btn", "Start processing"))),
            div(style="display: inline-block;vertical-align:top; width: 125px;", withBusyIndicatorUI(
              actionButton("ms_ls_s1_kc_abort_btn", "Abort processing")
            )),
            #"Output:",
            textOutput("processMS_ls_s1_kc")
          ), #close box
          #-----------------------------------------------------------------------------------------------------------------------------------
          #   #----------------------------------------------------------------------------------
          #   # Info Panel
          box(
            title = "Info Panel", status = "success", solidHeader= TRUE,
            
            tabBox(width = 700,
                   tabPanel("Progress Monitor",
                            tags$h4("Monitor the progress of a running process"),hr(),
                            verbatimTextOutput("ms_ls_s1_kc_progress"))
            )
          ) # close box
            
      )
)