#-----------------------------------------------------------------------------
# S1 Tab
tabItem(tabName = "s1_grd",
        fluidRow(
          #----------------------------------------------------------------------------------
          # Processing Panel Sentinel-1
          box(
            # Title                     
            title = "Sentinel-1 GRD processors", status = "success", solidHeader= TRUE,
            
            #tabBox(width = 700,
                   
              tags$h4("Sentinel-1 GRD processors"),
              hr(),
              #tags$b("Short description:"),
              p("The European Space Agency ESA provides Sentinel-1 data at", tags$b(" different levels of preprocessing."), tags$i("\"Ground Range Detected\" "), "(GRD) products 
                 have already undergone some important pre-processing steps. On the one hand, the applied processing leads to a slight decrease of geometric resolution 
                 and the loss of the phase information. On the other hand, data products exhibit less speckle noise and are already in", tags$b(" ground range"), " with approximate square pixels. 
                 In addition, those products are about 1/4th of the size with respect to", tags$i("\"Single Look Complex\" "), "(SLC) products and preprocessing time is considerably reduced."),
              p("SAR experts preferably use this type of data for applications where only the ", tags$b("amplitude measurement"), " is of interest. This includes basic concepts of data elaboration 
                 for land applications as well as flood monitoring and maritime applications such as ship or fish farm detection."),
              p("However, GRD datasets are not ready for analytical tasks and additional pre-processing (e.g. calibration, geocoding etc.) needs to be conducted. The Open SAR Toolkit provides 
                 ", tags$b("2 different processors"), " for the ennoblement of Sentinel-1 GRD products. Both routines are ", tags$b("fully-automatic"), " and produce datasets that can be easily imported into any 
                 RS/GIS software for the generation of value-added products, such as thematic maps."),
              p("The GRD to GTC processor generates", tags$b(" geometrically, terrain corrected (GTC)"), "products. It therefore corrects distortions due to the side-looking imaging geometry, and imagery is 
                 intercomparable due to image calibration and geocoding. This processor should be the first choice when working over ", tags$b("flat or maritime areas.")),
              p("The GRD to RTC processor generates ", tags$b("radiometrically, terrain corrected (RTC)"), " products. In contrast to the generation of GTC products, an additional processing step eliminates the 
                 ", tags$b("radiometric differences on slopes"), " with different orientation towards the sensor. While this step takes a ", tags$b("considerable amount of processing time,"), " it is favourable for 
                 ", tags$b("classification tasks over rugged terrain."), " Additionally, sea areas are masked out."),
              img(src = "S1_GRD2GTC/gtc_vs_rtc.jpeg", width = "100%", height = "100%"),
              tags$b("Figure 1: ", tags$i("left:")," GTC product showing a part of the Cordillera Oriental part of the Andes westwards of the city of Santa Cruz De La Sierra in Bolivia. ", tags$i("right:")," RTC product 
                      of the same area. Directional illumination effects of the slopes are eliminated by the terrain flattening procedure. Red areas (i.e. no-data) are affected by layover and shadow effects. Here the SAR cannot obtain
                      reliable information due to geometrical complexities."),br(),br(),
              p("The fact that both processors generate SAR backscatter as Gamma nought might confuse some of the users. As said before, the difference lies in the calibration procedure. The reference area of the backscatter 
                 for RTC products is based on the actual terrain (coming from auxiliary SRTM DEM) and is therefore normalised with respect to orientation towards the sensor. The GTC product, instead, uses a simplification 
                 of the earth model in form of an ellispoid which leads to distinct backscattering signatures along differently oriented slopes. Figure 2 gives an overview of SAR backscatter normalization convention according to Small 2011, 
                 and highlights the two outputs generated by the respective processor. "),
              img(src = "S1_GRD2GTC/gtc_vs_rtc2.jpeg", width = "100%", height = "100%"),
              tags$b("Figure 2: ", tags$i("Small et al. 2011"))
            
            #)
          ) # close box
          
        ) # close fluid row
) # close tabit
